local _G = GLOBAL
local TECH = _G.TECH
local Ingredient = _G.Ingredient

-- CTIY
AddRecipeToFilter("turf_foundation","SECRETKNOWLEDGE")
AddRecipeToFilter("turf_cobbleroad","SECRETKNOWLEDGE")
AddRecipeToFilter("city_lamp","SECRETKNOWLEDGE")
AddRecipeToFilter("pighouse_city","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_deli","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_general","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_hoofspa","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_produce","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_florist","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_antiquities","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_arcane","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_weapons","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_hatshop","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_bank","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_tinker","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_shop_cityhall_player","SECRETKNOWLEDGE")
AddRecipeToFilter("pig_guard_tower","SECRETKNOWLEDGE")
AddRecipeToFilter("securitycontract","SECRETKNOWLEDGE")
AddRecipeToFilter("playerhouse_city","SECRETKNOWLEDGE")
AddRecipeToFilter("hedge_block_item","SECRETKNOWLEDGE")
AddRecipeToFilter("hedge_cone_item","SECRETKNOWLEDGE")
AddRecipeToFilter("hedge_layered_item","SECRETKNOWLEDGE")
AddRecipeToFilter("lawnornament_1","SECRETKNOWLEDGE")
AddRecipeToFilter("lawnornament_2","SECRETKNOWLEDGE")
AddRecipeToFilter("lawnornament_3","SECRETKNOWLEDGE")
AddRecipeToFilter("lawnornament_4","SECRETKNOWLEDGE")
AddRecipeToFilter("lawnornament_5","SECRETKNOWLEDGE")
AddRecipeToFilter("lawnornament_6","SECRETKNOWLEDGE")  
AddRecipeToFilter("lawnornament_7","SECRETKNOWLEDGE")  