_G=GLOBAL
local STRINGS = _G.STRINGS
-- SPICE_CAFFEINPEPPER SPEECH

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_CAFFEINPEPPER = "커피를 갈았더니 후추향이 나네. 흥미로워."

STRINGS.CHARACTERS.WALTER.DESCRIBE.SPICE_CAFFEINPEPPER = "에취! 어떻게 이런 향이 나는 거지?"
STRINGS.CHARACTERS.WANDA.DESCRIBE.SPICE_CAFFEINPEPPER = "분명 후추콩처럼 붉기는 했었지만..."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SPICE_CAFFEINPEPPER = "의외의 곳에서 후추를 다시 만났어!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPICE_CAFFEINPEPPER = "고기에 뺴놓을 수 없는 향신료지!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPICE_CAFFEINPEPPER = "강렬한 향 만큼이나 커다란 힘을 가지고 있군."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPICE_CAFFEINPEPPER = "재채기 나올 것 같아!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPICE_CAFFEINPEPPER = "약간의 후추가루가 도움이 될때도 있겠지."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICE_CAFFEINPEPPER = "후추 같은 향을 풍기는군."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPICE_CAFFEINPEPPER = "저놈들 눈에 뿌려 보는 것도 좋을 것 같아."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SPICE_CAFFEINPEPPER = "흥미롭군. 마치 후추 같은데?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPICE_CAFFEINPEPPER = "강력한 볼프강의 코를 간지럽히다니! 강하다!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPICE_CAFFEINPEPPER = "킁킁. 뿌려두면 새들이 싫어하려나? 엣취!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SPICE_CAFFEINPEPPER = "에취! 에에취!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SPICE_CAFFEINPEPPER = "이 가루에게서 태풍과 같은 힘이 느껴지는군."
STRINGS.CHARACTERS.WURT.DESCRIBE.SPICE_CAFFEINPEPPER = "코가 매워!"
STRINGS.CHARACTERS.WX78.DESCRIBE.SPICE_CAFFEINPEPPER = "로봇은 재채기 따위 하지 않음"

-- PURIFICATION_TABLETS SPEECH

--[[STRINGS.CHARACTERS.GENERIC.DESCRIBE.PURIFICATION_TABLETS = "효과적인 정수법이야."

STRINGS.CHARACTERS.WALTER.DESCRIBE.PURIFICATION_TABLETS = "물을 정수할수 있는 알약이야."
STRINGS.CHARACTERS.WANDA.DESCRIBE.PURIFICATION_TABLETS = "불순물이 사라지지는 않겠지만...!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.PURIFICATION_TABLETS = "어우. 물맛이 좋아지지는 않겠지만..!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PURIFICATION_TABLETS = "이둔의 손길 그 자체로군!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PURIFICATION_TABLETS = "아, 정말 간단한 정수제로군."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PURIFICATION_TABLETS = "웩. 쓴 냄새가 나!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.PURIFICATION_TABLETS = "진흙탕을 마시는것보다는 나을거야,아마."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PURIFICATION_TABLETS = "아이오딘이 들어간 정수알약이라네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PURIFICATION_TABLETS = "불이 있는데 이게 왜 필요하지?"
STRINGS.CHARACTERS.WINONA.DESCRIBE.PURIFICATION_TABLETS = "정수용 알약이야. 없는것 보다는 낫겠지."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PURIFICATION_TABLETS = "이걸 물에 넣고 마시는데에 약간의 용기가 필요하겠어."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PURIFICATION_TABLETS = "이걸 마시는 물에 넣는다고?!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PURIFICATION_TABLETS = "이상한 냄새나"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PURIFICATION_TABLETS = "이걸 쓴다고 심리적 장벽이 사라지진 않을텐데."
STRINGS.CHARACTERS.WURT.DESCRIBE.PURIFICATION_TABLETS = "이 둥글둥글한거 원리가 궁금해!"
STRINGS.CHARACTERS.WX78.DESCRIBE.PURIFICATION_TABLETS = "화학적 처리를 통한 살균제."]]

-- DRUNK SPEECH

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DRUNK = "히끅... 나 취한 것 같아."

STRINGS.CHARACTERS.WALTER.ANNOUNCE_DRUNK = "으... 너무 어지러워."
STRINGS.CHARACTERS.WANDA.ANNOUNCE_DRUNK = "으어어... 세상이 빙글빙글 도는구먼!"
STRINGS.CHARACTERS.WARLY.ANNOUNCE_DRUNK = "후! 즐기되 취하지 말라 했었는데..."
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_DRUNK = "not_used_by_wigfrid"
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_DRUNK = "으윽... 과음한 것 같군."
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_DRUNK = "세상이 8개로 보여!!"
STRINGS.CHARACTERS.WENDY.ANNOUNCE_DRUNK = "아비게일? 너 어디갔어?"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_DRUNK = "이런, 너무 많이 마신 것 같아."
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_DRUNK = "흐헤헤... 화끈거리는데."
STRINGS.CHARACTERS.WINONA.ANNOUNCE_DRUNK = "집중하기가 힘들어..."
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_DRUNK = "으... 볼프강 갑자기 기분 이상하다."
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_DRUNK = "내가 지금 짐승인가 사람인가?"
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_DRUNK = "빙글빙글..."
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_DRUNK = "흐... 이게 기분이 좋다고?"
STRINGS.CHARACTERS.WURT.ANNOUNCE_DRUNK = "꼬르록, 머리 아프고 어지러워..."
STRINGS.CHARACTERS.WX78.ANNOUNCE_DRUNK = "연료 처리에 이상 발생"

-- DRUNK IMMUNITY SPEECH

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DRUNK_IMMUNITY = "이 정도로 날 취하게 할 수는 없어!"

STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_DRUNK_IMMUNITY = "열 잔이든 백 잔이든 이몸은 끄떡없다!"

-- END DRUNK SPEECH

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DRUNK_END = "좋아, 취기가 싹 사라졌어."

STRINGS.CHARACTERS.WALTER.ANNOUNCE_DRUNK_END = "한결 나아진 것 같아!"
STRINGS.CHARACTERS.WANDA.ANNOUNCE_DRUNK_END = "좋아,더 이상 시간을 낭비할 순 없어."
STRINGS.CHARACTERS.WARLY.ANNOUNCE_DRUNK_END = "고기 수프 좀 먹고 숙취를 풀어야겠어."
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_DRUNK_END = "이제 좀 낫군."
--STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_DRUNK_END = "not_used_by_wigfrid"
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_DRUNK_END = "이제 세상이 하나로 보여!"
STRINGS.CHARACTERS.WENDY.ANNOUNCE_DRUNK_END = "용기가 끝나니 ."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_DRUNK_END = "흠, ."
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_DRUNK_END = "으, 머리야... 멀쩡해진 건가?"
STRINGS.CHARACTERS.WINONA.ANNOUNCE_DRUNK_END = "어우, 다음에는 적당히 마셔야지."
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_DRUNK_END = "볼프강 쇠질해서 숙취 풀어야겠다."
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_DRUNK_END = "그래서 내가 지금 짐승인가? 아니, 그렇지는 않군."
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_DRUNK_END = "이제 괜찮아"
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_DRUNK_END = "필멸자들 취향은 참 특이하단 말이지. 흐유유!"
STRINGS.CHARACTERS.WURT.ANNOUNCE_DRUNK_END = "이제 괜찮아."
STRINGS.CHARACTERS.WX78.ANNOUNCE_DRUNK_END = "시스템 무결성 확인 완료"

-- END DRUNK BY SLEEP SPEECH

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_SLEEP_END = "자고 나니까 좀 상쾌하네!"

STRINGS.CHARACTERS.WALTER.ANNOUNCE_SLEEP_END = "역시 잠이 보약이야!"
STRINGS.CHARACTERS.WANDA.ANNOUNCE_SLEEP_END = "으으... 술 때문에 시간을 너무 많이 썼어."
STRINGS.CHARACTERS.WARLY.ANNOUNCE_SLEEP_END = "좋아, 한결 낫군."
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_SLEEP_END = "흠, 나쁘지 않군."
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_SLEEP_END = "좀 괜찮아진 것 같아!"
STRINGS.CHARACTERS.WENDY.ANNOUNCE_SLEEP_END = "차라리 깨어나지 못했으면 좋았을지도."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_SLEEP_END = "자고 일어나니 좀 괜찮아 진 것 같네."
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_SLEEP_END = "으, 머리야... 여긴 또 어디야?"
STRINGS.CHARACTERS.WINONA.ANNOUNCE_SLEEP_END = "이제 좀 낫군. 다시 일할 시간이야."
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_SLEEP_END = "볼프강 이제 다시 괞찮아졌다!"
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_SLEEP_END = "콜록 콜록, 움직여서 숙취를 좀 걷어내야겠어."
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_SLEEP_END = "더이상 보이지 않는 불 없어"
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_SLEEP_END = "자고 일어나니 좀 낫군."
STRINGS.CHARACTERS.WURT.ANNOUNCE_SLEEP_END = "나 이제 정말 괞찮아진것 같아."
STRINGS.CHARACTERS.WX78.ANNOUNCE_SLEEP_END = "시스템 무결성 확인 완료"

-- not ready to mliking

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_NOTCHARGE = "아직 젖이 나올 상태가 아니야."
STRINGS.CHARACTERS.WALTER.DESCRIBE.ANNOUNCE_NOTCHARGE = "어떻게 해야 염소로부터 우유를 얻을수 있을까?"
STRINGS.CHARACTERS.WANDA.DESCRIBE.ANNOUNCE_NOTCHARGE = "으어어... 난 번개가 칠때까지 기다릴 시간이 없어!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.ANNOUNCE_NOTCHARGE = "아직 젖이 불지 않았어."
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_NOTCHARGE = "그 유니콘은 아직 토르에게 선택받지 않았나니."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ANNOUNCE_NOTCHARGE = "그 염소는 아직 충전되지 않았다네."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ANNOUNCE_NOTCHARGE = "정말 귀찮은 염소야!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.ANNOUNCE_NOTCHARGE = "이 염소들는 한번 죽었다 살아나봐야 새끼를 키우나봐."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ANNOUNCE_NOTCHARGE = "젖을 짤 수 있는 상태가 아니란다."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ANNOUNCE_NOTCHARGE = "뿔에 번개 대신 불을 붙혀도 젖이 나올수 있지 않을까?"
STRINGS.CHARACTERS.WINONA.DESCRIBE.ANNOUNCE_NOTCHARGE = "저 염소를 충전시킬 필요가 있어."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ANNOUNCE_NOTCHARGE = "저 염소애게는 쥐어짜도 우유를 얻을수 없을거야!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ANNOUNCE_NOTCHARGE = "나에게 우유를 주시오! 염소씨."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.ANNOUNCE_NOTCHARGE = "예쁜 머리 나무가지에 번개 붙어야 한다"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.ANNOUNCE_NOTCHARGE = "그 염소를 괴롭혀도 젖이 나오진 않을거야."
STRINGS.CHARACTERS.WURT.DESCRIBE.ANNOUNCE_NOTCHARGE = "염소 젖이 안 나올거야, 뽀륵."
STRINGS.CHARACTERS.WX78.DESCRIBE.ANNOUNCE_NOTCHARGE = "경고:전력이 부족합니다."

STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "이걸 불속에 넣어도 아무 변화도 일어나지 않을거야."

STRINGS.CHARACTERS.WALTER.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "이걸 불 속에 넣을 필요는 없을것 같아."
STRINGS.CHARACTERS.WANDA.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "쓸데없는 짓이야."
STRINGS.CHARACTERS.WARLY.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "그렇게 해야 할 의미가 있나?"
STRINGS.CHARACTERS.WATHGRITHR.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "불이 그대를 거부할지니."
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "그럴 필요는 없을것 같군."
STRINGS.CHARACTERS.WEBBER.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "불속에 던지기 전에 생각해봤나요?"
STRINGS.CHARACTERS.WENDY.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "화장할수 없는 물건이야."
STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "그건 불 속에 넣어도 의미 없을것 같구나"
STRINGS.CHARACTERS.WILLOW.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "그렇게 하고 싶지만 소용없을거야."
STRINGS.CHARACTERS.WINONA.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "그렇게 하고 싶진 않군."
STRINGS.CHARACTERS.WOLFGANG.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "그게 맞나...?."
STRINGS.CHARACTERS.WOODIE.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "아니, 난 넣지 않을거야."
STRINGS.CHARACTERS.WORMWOOD.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "그것도 불 싫어해"
STRINGS.CHARACTERS.WORTOX.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "이 무슨 낭비람."
STRINGS.CHARACTERS.WURT.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "불에 이걸 왜 넣어? 뽀륵."
STRINGS.CHARACTERS.WX78.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "비 효율적 행동으로 판단됨"

-- GENERIC

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_DRILLING = "구멍을 파고 있는 중이야."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_DRILLING_ITEM = "물을 긷기 위해 우물을 파는 장치야."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOLE = "바닥이 보이지 않을정도로 깊어."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_EMPTY = "여기에 물을 채울수 있지, 혹은 다른 것 들도."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_CLEAN = "물이 채워져 있어."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_DIRTY = "물이 차있지만, 더러워."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_SALTY = "물이 차있지만, 짠내가 나."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_ICE = "이대로는 쓸 수 없겠어.하지만 어떻게든 꺼내볼수 있을것 같은데?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_TREE = "이건 찻잎을 재배할수 있는 나무야."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_TEA_TREE = "잎에서 풍부한 향이 느껴져."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED = "차나무의 열매야!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED_COOKED = "이런 행동은 하지 말았어야 했는데."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED_SAPLING = "시간이 지나면 나무로 자랄거야."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEALEAVES = "향이 정말 굉장한데?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEALEAVES_DRIED = "찻잎의 향기가 더 깊어진것 같은데?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_CAFFEINBERRY = "내가 사랑하는법을 알려 줄 식물이야."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY = "땅속에 단단히 뿌리내리고 있어."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_BEAN = "분명히 내가아는 커피콩과는 다르게 생긴것 같아."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "열이 확실하게 풍미를 깊게 만들었군.."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP = "마실것을 찾아보자."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CLEANWATER = "바로 마셔도 괜찮겠어."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DIRTY = "그냥 마시기에는 좀 위험하겠는데."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALTY = "이걸 마시는건 좋은 생각이 아닌것 같은데."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARBAGE = "내가 이 음료를 엉망으로 만들었네."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUIT = "과일향이 정말 달콤해."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BERRIES_TEA = "달콤한 베리향이 진해."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POMEGRANATE_TEA = "씨앗이 씹히는게 일품이겠어."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANA_TEA = "이국적인 향취가 느껴지는 음료야."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIG_TEA = "베리열매로 만든 차보다도 진한 단향이 나."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFRUIT_TEA = "향이 정말 좋은데!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLOWBERRY = "조리했는데도 여전히 빛을내고있어,이상하군."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_JUICE = "향을 맡는것 만으로도 힘이 넘치는군!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VEGGIE = "어...채소풋내가 나."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARROT_TEA = "제발 마실만 하기를."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CACTUS_TEA = "정말 이국적인 향이군."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MULLED = "아플때 이것만한게 없지!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREENTEA = "진짜 녹차같은데!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLACKTEA = "약간의 우유가 필요해."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLACKTEA_ICED = "정말 멋진데?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FUER = "이건 홍차도 녹차도 아니야, 이상하네."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MIXFLOWER = "향이 정말로 강렬하군."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HIBISCUS = "달콤한 동인도의 차야."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CACTUSFLOWER = "엄청나게 이국적인 차군."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUSFLOWER = "정말 예쁜 색을 띄고 있지만, 약간 진흙향이 나는군."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUSHIBISCUS = "과학으로는 설명할수 없겠어."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOILED_DRINK = "숙성되긴 커녕 썩어버렸어."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SODA = "톡 쏘는것 같아."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUITSODA = "훨씬 맛이 나아졌어!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LLSODA = "내 생각엔, 내가 새로운 종류의 음료를 발명한것 같은데?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COLA = "내가 이걸 다시 보게될줄은 생각치도 못했는데!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COLAQUANTUM = "이건 과학적으로 매우 뛰어난 정수야!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEER = "내가 이걸 다시 보게될줄은 생각치도 못했는데!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEAD = "이것 빛인가 아니면 어둠인가?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WINE = "매우 대중적인 음료지."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NOBLEWINE = "꿀처럼 달콤한 와인이야."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPARKLINGWINE = "파티에 들고 가기 좋지."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLOWBERRYWINE = "양조과정을 거쳤음에도 여전히 빛을 내는군.이상해라."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KUMIS = "유목민들의 전유물이지."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL = "이걸로 좀 더 쉽게 깨끗한 물을 얻을 수 있을거야."

STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "먼저 우물에 있는 것를 빼야해."
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.GIVE.WELL_BUSY = "지금 물을 긷고 있어."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DESALINATOR = {
	EMPTY = "이제 바다에서도 신선한 물을 얻을 수 있겠어!",
	PURIFY = "이 기계 일 잘하네!",
	HASWATER = "정수가 완료되었어.",
	BURNT = "불이 물을 이기다니, 이상하군.",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BARREL = {
	GENERIC = "이곳에 물을 저장할수 있어.",
	BURNT = "불이 물을 이기다니, 이상하군.",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BREWERY = {
	EMPTY = "식수를 오래동안 즐길수 있는 방법중 하나야.",
	BURNT = "불이 물을 이기다니, 이상하군.",
	FERMENTING_LONG = "조금 기다려야 할거야.",
	FERMENTING_SHORT = "거의 다 되어가고 있어!",
	DONE = "음...! 마실 준비가 다 되었어! 이제 컵을 가져와야 겠어.",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAMPKETTLE_ITEM = "생존의 1법칙.'깨끗한 물 없이는 아무것도 지속할 수 없다'"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAMPKETTLE = {
	GENERIC = "그저 바라보기만 해도 목이 타는군",
	BOILING_LONG = "충분히 기다려야 할거야.",
	BOILING_SHORT = "거의 다 된것 같아!",
	DONE = "마침내! 나는 깨끗한 물을 얻었어.",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KETTLE = {
	EMPTY = "그저 바라보기만 해도 목이 타는군.",
	BURNT = "불이 물을 이기다니, 이상하군.",
	BOILING_LONG = "충분히 기다려야 할거야.",
	BOILING_SHORT = "거의 다 된것 같아!",
	DONE = "음! 이제 마실 준비가 됐어! 그럼 이제 컵을 가져와야 겠어.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "요리사 친구의 휴대용 티포트 세트야.",
	EMPTY = "그저 바라보기만 해도 목이 타는군.",
	BOILING_LONG = "만드는 데에 시간이 좀 걸리겠어.",
	BOILING_SHORT = "거의 다 된것 같아!",
	DONE = "다 됐다!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}


-- WALTER -- 호기심 많은 보이스카우트 소년

STRINGS.CHARACTERS.WALTER.DESCRIBE.WELL_DRILLING = "구멍을 파고 있어."--
STRINGS.CHARACTERS.WALTER.DESCRIBE.WELL_DRILLING_ITEM = "이걸로 땅속의 물을 얻을수 있을거야."--

STRINGS.CHARACTERS.WALTER.DESCRIBE.HOLE = "물소리가 들리는것 같아!"--

STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_EMPTY = "이걸로 물을 길으면 될것 같아."
STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_CLEAN = "물이 한가득이야."
STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_DIRTY = "색이 좀 탁한것 같은데?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_SALTY = "짠내가 나!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_ICE = "얼음이 빠지지 않을것 같아. 이럴때는..."

STRINGS.CHARACTERS.WALTER.DESCRIBE.TEA_TREE = "멀리서부터 풀냄새가 느껴졌어."
STRINGS.CHARACTERS.WALTER.DESCRIBE.DUG_TEA_TREE = "손에 들면 풀내음이 진동해."
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEA_SEED = "화려한 열매네, 씨가 너무 크지만."
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEA_SEED_COOKED = "익히면 씨를 먹을수 있지 않을까?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEA_SEED_SAPLING = "무럭무럭 자라라."
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEALEAVES = "생 찻잎은 처음봐!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEALEAVES_DRIED = "향이 더 강해진것 같아"

STRINGS.CHARACTERS.WALTER.DESCRIBE.DUG_CAFFEINBERRY = "어딘가 옮겨심어야 겠어."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAFFEINBERRY = "난 공짜커피를 거절하지 않는 법을 배웠어."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAFFEINBERRY_BEAN = "커피 열매는 처음 보는데 이렇게 생겼던가?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "이제 좀 커피 생두 같을지도?"

STRINGS.CHARACTERS.WALTER.DESCRIBE.CUP = "가방에 매달을 컵 하나쯤은 있어야지."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CLEANWATER = "깨끗한 물이 담겨있어."
STRINGS.CHARACTERS.WALTER.DESCRIBE.DIRTY = "이런 물은 마셔서 안된다고 본 것 같은데."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SALTY = "마시면 갈증을 유발할거야."
STRINGS.CHARACTERS.WALTER.DESCRIBE.GARBAGE = "아무래도 엉망이 된것 같아."
STRINGS.CHARACTERS.WALTER.DESCRIBE.FRUIT = "달콤한 과일향이 풍부해."
STRINGS.CHARACTERS.WALTER.DESCRIBE.BERRIES_TEA = "새콤달콤한 향이 나."
STRINGS.CHARACTERS.WALTER.DESCRIBE.POMEGRANATE_TEA = "여성분들에게 좋다고 들었어!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BANANA_TEA = "바나나를 이렇게 먹을수도 있구나."
STRINGS.CHARACTERS.WALTER.DESCRIBE.FIG_TEA = "정말 달것 같아."
STRINGS.CHARACTERS.WALTER.DESCRIBE.DRAGONFRUIT_TEA = "향이 정말 좋아, 단맛은 강하지 않지만."
STRINGS.CHARACTERS.WALTER.DESCRIBE.GLOWBERRY = "빛을 내고 있는데 마셔도 될까?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAFFEINBERRY_JUICE = "나에겐 좀 쓸 것 같은데."
STRINGS.CHARACTERS.WALTER.DESCRIBE.VEGGIE = "채소향이 가득해."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CARROT_TEA = "당근쥬스였으면 차라리 나았을텐데.."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CACTUS_TEA = "가시가 아직 있을수 있으니깐 조심히 마셔야겠어."
STRINGS.CHARACTERS.WALTER.DESCRIBE.MULLED = "아플때 마시는 술이라고 들었어!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.GREENTEA = "선선한 녹색을 띄고 있어!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BLACKTEA = "차 마실 시간이야."
STRINGS.CHARACTERS.WALTER.DESCRIBE.BLACKTEA_ICED = "향긋하고 시원해."
STRINGS.CHARACTERS.WALTER.DESCRIBE.FUER = "정말 진하게 우려냈나봐."
STRINGS.CHARACTERS.WALTER.DESCRIBE.MIXFLOWER = "꽃향기가 가득해."
STRINGS.CHARACTERS.WALTER.DESCRIBE.HIBISCUS = "정말 달콤한 꽃향기가 나."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CACTUSFLOWER = "아름다운 꽃이 장식되어 있어."
STRINGS.CHARACTERS.WALTER.DESCRIBE.LOTUSFLOWER = "정말 예쁜 색의 음료야.조금 흙냄새가 나는것 같지만."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SUSHIBISCUS = "정말 예쁜 꽃이 들어있어.뭔가 조금 불길한 느낌이 드는것 같지만."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SPOILED_DRINK = "음....아무래도 뭔가 잘못된것 같아."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SODA = "와! 나 이거 정말 좋아해."
STRINGS.CHARACTERS.WALTER.DESCRIBE.FRUITSODA = "과일향이 나는 소다야! 난 이게 정말 좋아."
STRINGS.CHARACTERS.WALTER.DESCRIBE.LLSODA = "정말 달콤하고 시원할것 같아!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.COLA = "많이 마시면 이가 썩는다고 지겹게 들었어."
STRINGS.CHARACTERS.WALTER.DESCRIBE.COLAQUANTUM = "스스로 빛을 내는 콜라라니 정말 놀라워!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BEER = "이건 맥주야. 내가 마셔도 되는걸까?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.MEAD = "이건 벌꿀주야. 내가 마셔도 되는걸까?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.WINE = "이건 적포도주야. 내가 마셔도 되는걸까?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.NOBLEWINE = "이건 귀부와인이야. 내가 마셔도 되는걸까?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.SPARKLINGWINE = "이건 탄산이 들어간 와인이야. 내가 마셔도 되는걸까?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.GLOWBERRYWINE = "빛을 내고 있는 와인이야. 신기하지만, 내가 마셔도 되는걸까?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.KUMIS = "유목민들이 우유를 오래 보관하기위해 만든 술이라고 들었어. 하지만 내가 마셔도 되는지는 모르겠어."

STRINGS.CHARACTERS.WALTER.DESCRIBE.WELL = "지하에서 흐르는 물소리가 들려와!"

STRINGS.CHARACTERS.WALTER.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "물을 퍼올 물건을 가져와야겠어"
STRINGS.CHARACTERS.WALTER.ACTIONFAIL.GIVE.WELL_BUSY = "양동이가 두개나 들어가진 않을것 같아."

STRINGS.CHARACTERS.WALTER.DESCRIBE.DESALINATOR = {
	EMPTY = "이걸로 바닷물에서 소금기를 분리해낼수 있을거야.",
	PURIFY = "물을 내리는중이야.",
	HASWATER = "이제 깨끗한 물을 얻을수 있어.",
	BURNT = "불을 끌 수 있을정도의 물이 없었나봐",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.BARREL = {
	GENERIC = "와우, 정말 큰 나무통인데?",
	BURNT = "불을 끌 수 있을정도의 물이 없었나봐",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.BREWERY = {
	GENERIC = "안에 음료가 있었으면 정말 좋겠어.",
	BURNT = "불을 끌 수 있을정도의 물이 없었나봐",
	FERMENTING_LONG = "이 일은 시간이 좀 걸릴거야. 그 사이에 내가 발견한 멋진 벌레를 보지 않을래?",
	FERMENTING_SHORT = "음료가 거의 다 완성되었어!",
	DONE = "와서 음료를 가져가!",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPKETTLE = {
	GENERIC = "안에 음료가 있었으면 정말 좋겠어.",
	BOILING_LONG = "이 일은 시간이 좀 걸릴거야. 그 사이에 내가 발견한 멋진 벌레를 보지 않을래?",
	BOILING_SHORY = "음료가 거의 다 완성되었어!",
	DONE = "와서 음료를 가져가!",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.KETTLE = {
	GENERIC = "안에 음료가 있었으면 정말 좋겠어.",
	BURNT = "불을 끌 수 있을정도의 물이 없었나봐",
	BOILING_LONG = "이 일은 시간이 좀 걸릴거야. 그 사이에 내가 발견한 멋진 벌레를 보지 않을래?",
	BOILING_SHORT = "음료가 거의 다 완성되었어!",
	DONE = "와서 음료를 가져가!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "그래도 재대로 준비된 주전자만큼은 못해.",
	EMPTY = "음료를 준비하려면 재료를 좀 채집해야 할 거야.",
	BOILING_LONG = "기다리는동안 잡아온 곤충컬렉션을 정리할수 있을거야.",
	BOILING_SHORT = "음료가 거의 다 완성되었어!",
	DONE = "으음, 음료를 마실시간이다!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WANDA

STRINGS.CHARACTERS.WANDA.DESCRIBE.WELL_DRILLING = "빨리빨리 뚫으라고!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.WELL_DRILLING_ITEM = "일단 이것부터 작동시켜야겠어."

STRINGS.CHARACTERS.WANDA.DESCRIBE.HOLE = "실수로라도 빠지지 않도록 조심해야겠어."

STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_EMPTY = "조금 엉성해 보이지만, 써야 해."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_CLEAN = "깨끗해 보이는군."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_DIRTY = "정말 급한게 아니라면 마시지 않는게 좋겠어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_SALTY = "요리할떄 쓰면 간을 따로 안 맞춰도 되겠네!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_ICE = "돌덩이처럼 딱딱해져 버렸군."

STRINGS.CHARACTERS.WANDA.DESCRIBE.TEA_TREE = "차나무야. 잎을 얻으려면 보기보다 고생이 많이 들어갈거야."
STRINGS.CHARACTERS.WANDA.DESCRIBE.DUG_TEA_TREE = "차 한잔 할 여유라도 있었으면 좋겠네."
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEA_SEED = "먹을게 없는 열매로군."
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEA_SEED_COOKED = "시간만 낭비했어!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEA_SEED_SAPLING = "얘는 시간이 해결해 줄거야."
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEALEAVES = "찻잎이야.끓는 물에 넣기만 하면 되던가?"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEALEAVES_DRIED = "말린 이파리야.끓는 물에 넣어버리자."

STRINGS.CHARACTERS.WANDA.DESCRIBE.DUG_CAFFEINBERRY = "아이고야, 얼른 열매를 맺기를 바라자."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CAFFEINBERRY = "정말 탐나는 과육식물이로군."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CAFFEINBERRY_BEAN = "오호라,이 열매는 시간을 아끼는데 큰 도움이 될거야"
STRINGS.CHARACTERS.WANDA.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "그만한 가치가 있겠지!"

STRINGS.CHARACTERS.WANDA.DESCRIBE.CUP = "마실걸 찾아야 겠어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CLEANWATER = "바로 마실수 있겠어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.DIRTY = "정말 급한게 아니라면 마시지 않는게 좋겠어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.SALTY = "요리할떄 쓰면 간을 따로 안 맞춰도 되겠네!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.GARBAGE = "이 무슨 시간낭비람!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.FRUIT = "달콤해서 얼른 마실수 있겠어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BERRIES_TEA = "따자마자 바로 먹어도 좋았을것 같은데."
STRINGS.CHARACTERS.WANDA.DESCRIBE.POMEGRANATE_TEA = "열매의 씨앗을 골라내서 먹는것보다 마셔버리는게 빠르겠지."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BANANA_TEA = "그냥 바로 먹는게 간편하고 좋겠어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.FIG_TEA = "내게는 익숙하지 않은 향이로군."
STRINGS.CHARACTERS.WANDA.DESCRIBE.DRAGONFRUIT_TEA = "향이 나쁘진 않네."
STRINGS.CHARACTERS.WANDA.DESCRIBE.GLOWBERRY = "빛이 나는 음료라, 분명 위험할것 같은데."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CAFFEINBERRY_JUICE = "향만 맡아도 젊음을 되 찾는것 같구먼!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.VEGGIE = "건강에는 좋을것 같네."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CARROT_TEA = "맛을 가릴 시간이 없어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CACTUS_TEA = "가시를 골라내지 않아도 좋기를 바래."
STRINGS.CHARACTERS.WANDA.DESCRIBE.MULLED = "아아, 비가오는날에는 이런걸 마셔줘야 하지."
STRINGS.CHARACTERS.WANDA.DESCRIBE.GREENTEA = "이제 버터를 바른 토스트만 있으면 되겠군."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BLACKTEA = "티 타임을 가지기에는 내가 너무 바쁘구먼."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BLACKTEA_ICED = "급하게 마셔도 입천장이 데지 않는건 좋아."
STRINGS.CHARACTERS.WANDA.DESCRIBE.FUER = "내가 지금 찻잎을 가릴 때가 아니야."
STRINGS.CHARACTERS.WANDA.DESCRIBE.MIXFLOWER = "꽃잎이 마시는데 방해되."
STRINGS.CHARACTERS.WANDA.DESCRIBE.HIBISCUS = "향은 대단하지만,꽃잎이 마시는데 방해되."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CACTUSFLOWER = "이것도 가시가 남아있나?"
STRINGS.CHARACTERS.WANDA.DESCRIBE.LOTUSFLOWER = "아이고 이런,또 다른 꽃 차네."
STRINGS.CHARACTERS.WANDA.DESCRIBE.SUSHIBISCUS = "향은 대단하지만,꽃잎이 마시는데 방해되."
STRINGS.CHARACTERS.WANDA.DESCRIBE.SPOILED_DRINK = "시간만 엄청 낭비했군!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.SODA = "단숨에 마시기에는 목이 따끔거릴거야."
STRINGS.CHARACTERS.WANDA.DESCRIBE.FRUITSODA = "과일향이 나지만 단숨에 마시기는 힘들거야."
STRINGS.CHARACTERS.WANDA.DESCRIBE.LLSODA = "달지만 탄산때문에 마시기 힘들어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.COLA = "흥미롭군.이건 콜라야."
STRINGS.CHARACTERS.WANDA.DESCRIBE.COLAQUANTUM = "빛이 나는 음료라, 분명 위험할것 같은데."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BEER = "음료의 형상을 한 빵이지."
STRINGS.CHARACTERS.WANDA.DESCRIBE.MEAD = "꿀을 더 오래 보관하려 한건가?"
STRINGS.CHARACTERS.WANDA.DESCRIBE.WINE = "향을 음미할 여유가 없어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.NOBLEWINE = "달콤해서 이쪽이 마시기는 좋지."
STRINGS.CHARACTERS.WANDA.DESCRIBE.SPARKLINGWINE = "아이고 이런, 탄산도 있고 알콜도 있어."
STRINGS.CHARACTERS.WANDA.DESCRIBE.GLOWBERRYWINE = "빛이 나는 음료라, 분명 위험할것 같은데."
STRINGS.CHARACTERS.WANDA.DESCRIBE.KUMIS = "지금 마실것을 가릴 떄가 아니야."

STRINGS.CHARACTERS.WANDA.DESCRIBE.WELL = "적어도 물 걱정은 안해도 되겠어"

STRINGS.CHARACTERS.WANDA.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "얼른 양동이를 가져와!"
STRINGS.CHARACTERS.WANDA.ACTIONFAIL.GIVE.WELL_BUSY = "빨리빨리!"

STRINGS.CHARACTERS.WANDA.DESCRIBE.DESALINATOR = {
	EMPTY = "급한대로 이거라도 써야겠어.",
	PURIFY = "기다리다 사람 복장 터지겠구먼.",
	HASWATER = "드디어!",
	BURNT = "아이고 이런, 다 끝이로구먼.",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.BARREL = {
	GENERIC = "물을 저장할 시간에 한잔이라도 더 마시는게 낫겠어.",
	BURNT = "아이고 이런, 다 끝이로구먼.",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.BREWERY = {
	GENERIC = "차라리 그냥... 베리나 당근을 채칩해서 먹든지 해야겠다.",
	BURNT = "아이고 이런, 다 끝이로구먼.",
	FERMENTING_LONG = "내가 이래서 이 짓를 싫어해. 끝날 기미가 안보이잖아!",
	FERMENTING_SHORT = "지금쯤 음료가 완성이 됬겠지?",
	DONE = "마침내 음료가 다 됐군!",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPKETTLE_ITEM = "어째서 자연에는 바로 마실만한 깨끗한 수원이 없는거지?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPKETTLE = {
	GENERIC = "내가 물을 챙겼던가?",
	BOILING_LONG = "으어어 빨리빨리 했으면 좋겠어!",
	BOILING_SHORY = "이제 더 오래 걸리지는 않겠지?",
	DONE = "드디어!",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.KETTLE = {
	GENERIC = "차라리 그냥... 베리나 당근을 채칩해서 먹든지 해야겠다.",
	BURNT = "아이고 이런, 다 끝이로구먼.",
	BOILING_LONG = "내가 이래서 이 짓를 싫어해. 끝날 기미가 안보이잖아!",
	BOILING_SHORT = "지금쯤 음료가 완성이 됬겠지?",
	DONE = "마침내 음료가 다 됐군!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "난 고급 음료니 뭐니 귀찮아서 싫어.",
	EMPTY = "차라리 그냥... 베리나 당근을 채칩해서 먹든지 해야겠다.",
	BOILING_LONG = "으어어 빨리빨리 했으면 좋겠어!",
	BOILING_SHORT = "이제 더 오래 걸리지는 않겠지?",
	DONE = "마침내 음료가 다 됐군!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WARLY

STRINGS.CHARACTERS.WARLY.DESCRIBE.WELL_DRILLING = "암반수를 찾는중이야."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WELL_DRILLING_ITEM = "잡맛이 없는 깨끗한 물은 기본중에 기본이지."

STRINGS.CHARACTERS.WARLY.DESCRIBE.HOLE = "물의 정령이 나에게 노래하는것 같군!"

STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_EMPTY = "냄비 대용으로 쓸수는 없겠어."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_CLEAN = "깨끗해 보이는군!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_DIRTY = "아니야...다른방법이 없을까?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_SALTY = "이걸로 간을 맞출 생각은 꿈도 꾸지 마."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_ICE = "얼음은 깨끗하군! 빼낼 방법을 찾아봐야겠어."

STRINGS.CHARACTERS.WARLY.DESCRIBE.TEA_TREE = "마드모아젤. 당신에게서 매력적인 향이 나는군요?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.DUG_TEA_TREE = "그대를 내 파티에 초대해도 될까요?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEA_SEED = "차 나무의 열매야. 식품으로써의 가치는 거의 없어."
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEA_SEED_COOKED = "이게 정말 옳은 선택이였을까?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEA_SEED_SAPLING = "그저 어린 아기일 뿐이야."
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEALEAVES = "음....!향기로워."
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEALEAVES_DRIED = "정말 우아한 향이야."

STRINGS.CHARACTERS.WARLY.DESCRIBE.DUG_CAFFEINBERRY = "땅에 다시 심어주는게 좋겠어."
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAFFEINBERRY = "저 덤불에서 자라난건...커피콩?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAFFEINBERRY_BEAN = "영광이야!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "이제 뜨거운 물만 있으면...!"

STRINGS.CHARACTERS.WARLY.DESCRIBE.CUP = "차를 위하여!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CLEANWATER = "마실만해."
STRINGS.CHARACTERS.WARLY.DESCRIBE.DIRTY = "아니야...마셔서는 안될것 같아."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SALTY = "물에서 비린내를 제거해야 겠는데?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.GARBAGE = "내 부주방장들은 이 끔찍한 광경을 못 볼 테니 다행이야..."
STRINGS.CHARACTERS.WARLY.DESCRIBE.FRUIT = "으음....! 정말 달콤한 향이야.."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BERRIES_TEA = "5가지 향이 나는것 같군."
STRINGS.CHARACTERS.WARLY.DESCRIBE.POMEGRANATE_TEA = "열매째로 가열하기보다는 즙을 짜내는쪽이 좋았겠지만..."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BANANA_TEA = "껍질을 같히 가열할 생각을 한건 누구지?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.FIG_TEA = "이 진한 꿀향과 약간의 과일향....!."
STRINGS.CHARACTERS.WARLY.DESCRIBE.DRAGONFRUIT_TEA = "은은하고 나쁘지 않아."
STRINGS.CHARACTERS.WARLY.DESCRIBE.GLOWBERRY = "재료의 특색이 정말 잘 살아있어."
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAFFEINBERRY_JUICE = "대박!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.VEGGIE = "음....!정말 건강해지는 향이야."
STRINGS.CHARACTERS.WARLY.DESCRIBE.CARROT_TEA = "의외로 실존하는 차야."
STRINGS.CHARACTERS.WARLY.DESCRIBE.CACTUS_TEA = "씹히는 과육이 일품이야."
STRINGS.CHARACTERS.WARLY.DESCRIBE.MULLED = "...어머니는 건강하시려나."
STRINGS.CHARACTERS.WARLY.DESCRIBE.GREENTEA = "정말 훌룡해!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BLACKTEA = "이제 한조각의 케이크만 있으면 좋겠네."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BLACKTEA_ICED = "레몬주스가 없는게 조금 아쉽네."
STRINGS.CHARACTERS.WARLY.DESCRIBE.FUER = "흠...어디 한번?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.MIXFLOWER = "꽃 역시 차의 재료로 손색이 없지."
STRINGS.CHARACTERS.WARLY.DESCRIBE.HIBISCUS = "열대의 향취가 흠껏 느껴지는군!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CACTUSFLOWER = "대부분의 선인장에는 독이 있지.여기는 그렇지 않아서 다행이야."
STRINGS.CHARACTERS.WARLY.DESCRIBE.LOTUSFLOWER = "앙코르와트에 와 있는 기분이야."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SUSHIBISCUS = "음....?이건 히비스커스인가?."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SPOILED_DRINK = "아이고,변질되어버렸네.."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SODA = "고기를 연하게 만드는데에도 쓸수 있어."
STRINGS.CHARACTERS.WARLY.DESCRIBE.FRUITSODA = "고급진 요리에는 어울리지 않아."
STRINGS.CHARACTERS.WARLY.DESCRIBE.LLSODA = "많이 마시면 이가 썩는다네."
STRINGS.CHARACTERS.WARLY.DESCRIBE.COLA = "정크푸드의 단짝친구지."
STRINGS.CHARACTERS.WARLY.DESCRIBE.COLAQUANTUM = "정말 신기하군!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BEER = "물 대신 마시지 않도록 조심해!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.MEAD = "음...!벌들이 정말 열심히 일한 모양이군."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WINE = "음...!바디가 좀 약한가?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.NOBLEWINE = "단맛의 원인이 곰팡이라는걸 아는 사람이 있을지 모르겠네."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SPARKLINGWINE = "누구에게나 가볍게 추천할만하지."
STRINGS.CHARACTERS.WARLY.DESCRIBE.GLOWBERRYWINE = "음....!정말 신비로운 와인이야."
STRINGS.CHARACTERS.WARLY.DESCRIBE.KUMIS = "세계에서 가장 혐오스러운 음료라는건 오해야!"

STRINGS.CHARACTERS.WARLY.DESCRIBE.WELL = "잡맛이 없는 깨끗한 물은 기본중에 기본이지."

STRINGS.CHARACTERS.WARLY.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "물을 길을 양동이를 가져와야겠어"
STRINGS.CHARACTERS.WARLY.ACTIONFAIL.GIVE.WELL_BUSY = "먼저 내려간 양동이가 있어."

STRINGS.CHARACTERS.WARLY.DESCRIBE.DESALINATOR = {
	EMPTY = "해수에서 소금과 물을 분리해줄거야",
	PURIFY = "시간이 조금 걸릴거야",
	HASWATER = "마실 물이 있나 볼까?",
	BURNT ="불이 정말로 목이 말랐나 보네.",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.BARREL = {
	GENERIC = "여기에 물을 저장할수 있어.",
	BURNT = "불이 정말로 목이 말랐나 보네.",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.BREWERY = {
	GENERIC = "양조기도 비고, 내 맘도 비었네.",
	BURNT = "커다란 몰로토프 칵테일이였어.",
	FERMENTING_LONG = "걸작은 시간이 걸리는 편이지.",
	FERMENTING_SHORT = "거의 다 됬어...",
	DONE = "으흐흐, 완성!",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.CAMPKETTLE_ITEM = "물 정도는 끓일수 있겠어"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAMPKETTLE = {
	GENERIC = "부재료를 넣기에는 좀 열악해 보이네",
	BOILING_LONG = "아직 덜 익었어.",
	BOILING_SHORY = "조금 더 뜸을 들여야 해.",
	DONE = "이제 마셔도 좋을것 같아.",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.KETTLE = {
	GENERIC = "주전자도 비고, 내 맘도 비었네.",
	BURNT = "비극적이야.",
	BOILING_LONG = "걸작은 시간이 걸리는 편이지.",
	BOILING_SHORT = "거의 다 됬어...",
	DONE = "으흐흐, 완성!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "아, 나의 훌룡한 조수양, 오늘은 어디로 데이트하러 갈까?",
	EMPTY = "이것과 함께하는 길은 어디든 즐겁지!",
	BOILING_LONG = "향을 충분히 우려내는데에는 시간이 걸려.",
	BOILING_SHORT = "빨리 음료를 내가야 한다고!",
	DONE = "건져내! 아, 오래된 습관이야...",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WATHGRITHR

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WELL_DRILLING = "길들여지지 않은 대지에 대항할 강력한 무기로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WELL_DRILLING_ITEM = "나 이 대지가 샘물로 넘쳐흐름을 선포하노라!"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.HOLE = "물소리가 흘러 넘치는구나."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_EMPTY = "평범한 양동이로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_CLEAN = "가득찬 양동이로군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_DIRTY = "진정한 전사는 사소한건 신경쓰지 않는법이라."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_SALTY = "로키의 속삭임과 같도다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_ICE = "요쿨의 숨결이 닿았도다."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_TREE = "향기로운 나무로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUG_TEA_TREE = "땅의 여신께 되돌아 갔으면 좋겠구나"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_SEED = "볼품없는 과실이로군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_SEED_COOKED = "불에 구워진 볼품없는 과실이로군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_SEED_SAPLING = "어린 나무로도다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEALEAVES = "향기로운 이파리 모듬이로군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEALEAVES_DRIED = "말린 향기로운 이파리 모듬이로다."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUG_CAFFEINBERRY = "땅의 여신께 되돌아 갔으면 좋겠구나"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAFFEINBERRY = "모래속에 매복한 전사의 풍채로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAFFEINBERRY_BEAN = "나의 검정빛을 취하겠노라"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "활력을 주는 향이 나오는구나."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CUP = "자그마한 컵이로도다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CLEANWATER = "마심을 허하노라"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DIRTY = "진정한 전사는 사소한건 신경쓰지 않는법이라."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALTY = "로키의 속삭임과 같도다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GARBAGE = "음식물 찌거기로군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FRUIT = "과일들을 우려낸 음료로군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BERRIES_TEA = "대지신의 피로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.POMEGRANATE_TEA = "과육의 피로 가득하도다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BANANA_TEA = "원숭이들의 음료로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FIG_TEA = "무화과 과육을 우려냈도다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DRAGONFRUIT_TEA = "더 이상 화려하지 않구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GLOWBERRY = "마치 요정들의 샘물에서 퍼온것 같구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAFFEINBERRY_JUICE = "쓰고 심장을 크게 울리게 하구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VEGGIE = "아, 더할나위 없는 약자들의 음료로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CARROT_TEA = "냄새만 맡아도 역하구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CACTUS_TEA = "그 풀 역시 전사였다라고 할수있겠노라."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MULLED = "진정한 전사는 뭐든 싸움으로 이겨내는 법."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GREENTEA = "향기로운 차 로군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BLACKTEA = "향기로운 홍차 이로군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BLACKTEA_ICED = "차가운 홍차이니라."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FUER = "이파리 우린 검은 차로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MIXFLOWER = "프레야의 손길이 닿은 음료로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.HIBISCUS = "정말 커다란 꽃 한송이가 들어있구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CACTUSFLOWER = "남국의 꽃이 장식되어 있도다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LOTUSFLOWER = "프레야의 미모와 같은 음료로구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUSHIBISCUS = "헬라의 꽃이 장식되어 있구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPOILED_DRINK = "시간은 이 음료에게 현명함이 아니라 역겨움을 주었군."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SODA = "소다이니라."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FRUITSODA = "과일 섞은 소다이니라."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LLSODA = "아이들의 음료로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COLA = "아아, 또 다른 신화속 음료로구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COLAQUANTUM = "미미르의 샘물과도 같구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEER = "게르만의 맥주로구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MEAD = "노르드의 미드로도다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WINE = "적포도주로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NOBLEWINE = "흰 포도주로구나."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPARKLINGWINE = "연회용 포도주로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GLOWBERRYWINE = "마치 요정들이 양조한것 같구나 ."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KUMIS = "카자흐의 크므즈로다."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WELL = "우물이로다."

STRINGS.CHARACTERS.WATHGRITHR.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "퍼 올릴것이 필요하니라."
STRINGS.CHARACTERS.WATHGRITHR.ACTIONFAIL.GIVE.WELL_BUSY = "그렇게 할 순 없도다."

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DESALINATOR = {
	EMPTY = "해수로부터 소금기를 제거해 준다네.",
	PURIFY = "기다리는동안 내가 다른일을 할수 있겠지.",
	HASWATER = "이제 마실수 있나?",
	BURNT = "불이 먹이사슬의 정점에 섰도다.",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BARREL = {
	GENERIC = "물을 보관할 곳이로다.",
	BURNT = "불이 먹이사슬의 정점에 섰도다.",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BREWERY = {
	GENERIC = "아무것도 없군.",
	BURNT = "불이 먹이사슬의 정점에 섰도다.",
	FERMENTING_LONG = "기다리는동안 내가 다른일을 할수 있겠지.",
	FERMENTING_SHORT = "오래걸리지 않을거야!",
	DONE = "무엇이 나왔지?",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAMPKETTLE_ITEM = "휴대용 주전자로다."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAMPKETTLE = {
	GENERIC = "아무것도 없군",
	BOILING_LONG = "기다리는동안 내가 다른일을 할수 있겠지.",
	BOILING_SHORY = "오래걸리지 않을거야!",
	DONE = "마심을 허하노라.",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KETTLE = {
	EMPTY = "아무것도 없군.",
	BURNT = "불이 먹이사슬의 정점에 섰도다.",
	BOILING_LONG = "기다리는동안 내가 다른일을 할수 있겠지.",
	BOILING_SHORT = "오래걸리지 않을거야!",
	DONE = "무엇이 나왔지?",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "요리는 고귀한 직업이로다.",
	EMPTY = "아무것도 없군.",
	BOILING_LONG = "갈증으로 내 목이 가렵도다...서둘러라, 주전자!",
	BOILING_SHORT = "이는 신속히 처리될것이다.",
	DONE = "무엇이 나왔지?",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WAXWELL

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WELL_DRILLING = "다행히 스스로 작동할 수 있는 모양이로군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WELL_DRILLING_ITEM = "농기계인가? 아니 조금 다르군."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.HOLE = "어이쿠, 이 안으로 굴러떨어지면 시체도 찾지 못하겠어."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_EMPTY = "물을 담을수 있는 버켓이야."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_CLEAN = "이대로 마시는건 개인적으로 사양이라네."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_DIRTY = "물색이 좀 탁하군. 마시지 않는게 좋겠어."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_SALTY = "마음에 안드는놈 얼굴을 담구는데 딱이야."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_ICE = "꽝꽝 얼어버렸군."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_TREE = "누가 차 한잔 내왔으면 좋겠네."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUG_TEA_TREE = "내가 정원사라도 되는줄 아는가?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_SEED = "누가 나무키울줄 아는 놈이 쓸모를 알겠지"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_SEED_COOKED = "삶아 죽였어."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_SEED_SAPLING = "허. 땅으로 가야 했던 모양이로군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEALEAVES = "그냥 만지면 손에 녹색물이 들겠어."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEALEAVES_DRIED = "누가 이걸로 차 한잔 내왔으면 좋겠네."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUG_CAFFEINBERRY = "확실히, 처음보는 식물과 하나가 되어 있어."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAFFEINBERRY = "본적없는 돌연변이로군....아니, 기생식물이 달라 붙은건가?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAFFEINBERRY_BEAN = "내가 아는 커피콩보다 이쪽이 더 커피콩 같네."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "생 원두보다는 낫지만 더 좋게 만들 방법이 있지 않는가?"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CUP = "개인위생 차원에서 중요하지."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CLEANWATER = "이 야생에서 깨끗한 물은 소중하지."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DIRTY = "물색이 좀 탁하군. 마시지 않는게 좋겠어."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SALTY = "어떤 놈 얼굴에 이걸 뿌려줄까."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GARBAGE = "정말 교양없군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FRUIT = "우아하고 지나치게 화려해."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BERRIES_TEA = "최소한의 교양은 지켰군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.POMEGRANATE_TEA = "그나마 구색은 갖췄군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BANANA_TEA = "정말 무례한 차야."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FIG_TEA = "정말 사치스런 차로군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DRAGONFRUIT_TEA = "덜 고급스러워 졌군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GLOWBERRY = "호기심 끄는데 정말 탁월한 미끼로군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAFFEINBERRY_JUICE = "기대되는군!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VEGGIE = "일종의 보르시치인가?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CARROT_TEA = "나는 이것보다 더 한것도 마셔봤어."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CACTUS_TEA = "자, 이제 누구의 승리인가?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MULLED = "아아...몸에 스며드는 매운향이 일품이지."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GREENTEA = "음....! 차 한잔 즐길 여유가 별로 없다는게 슬프구먼."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BLACKTEA = "나는 스트레이트가 취향이라네."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BLACKTEA_ICED = "얼음을 넣은건 내 입맛에는 안 맞아."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FUER = "이것도 차 인가?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MIXFLOWER = "팽형도 나쁘지 않지."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.HIBISCUS = "정말로 아름답기 짝이 없구먼."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CACTUSFLOWER = "이러니 더 보기 좋네."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LOTUSFLOWER = "겉 모습은 고급스럽군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUSHIBISCUS = "어둠의 정수로군."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPOILED_DRINK = "내가 숙성시킬수 있을거라 생각했는데 말이지."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SODA = "얘들 음료야."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FRUITSODA = "사치스런 얘들 음료야."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LLSODA = "싸구려 얘들 음료야."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COLA = "품격없는 식사에 어울리지."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COLAQUANTUM = "전쟁, 전쟁은 결코 변하지 않는다."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEER = "격없는 자리에나 어울리지."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MEAD = "이런 밀주라도 있는것에 감지덕지 해야 하나?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WINE = "더 고급진게 있으면 좋겠것만."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.NOBLEWINE = "아가씨 취향이야."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPARKLINGWINE = "의외로 보통 와인보다 비싸다네."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GLOWBERRYWINE = "양조할줄 아는 사람을 안다는게 얼마나 좋은 변화인지."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KUMIS = "나는 이것을 마실수 있...을거야."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WELL = "이제 시체는 못 밀어넣겠군."

STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "누구 수영할줄 아는 사람?"
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.GIVE.WELL_BUSY = "나는 인내심을 길러야 해..."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DESALINATOR = {
	EMPTY = "정수장치인가? 나는 이런거에 관심 없다만.",
	PURIFY = "나는 인내심을 길러야 해...",
	HASWATER = "다 걸려졌다네.",
	BURNT = "마르다 못해 타버렸군.",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BARREL = {
	GENERIC = "물을 보관하는 통",
	BURNT = "마르다 못해 타버렸군.",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BREWERY = {
	GENERIC = "생각만 해도 속이 시원해지는군",
	BURNT = "마르다 못해 타버렸군.",
	FERMENTING_LONG = "기다리자..",
	FERMENTING_SHORT = "거의 다 됬어!",
	DONE = "마침내, 마실만한게 나왔군.",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAMPKETTLE_ITEM = "누가 대신 들고다녀 줬으면 좋겠네."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAMPKETTLE = {
	GENERIC = "비어있어.",
	BOILING_LONG = "기다리자..",
	BOILING_SHORY = "이제 조금이야.",
	DONE = "이제 마셔도 되겠네.",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KETTLE = {
	GENERIC = "생각만 해도 속이 따뜻해지는군",
	BURNT = "마르다 못해 타버렸군.",
	BOILING_LONG = "기다리자..",
	BOILING_SHORT = "거의 다 됬어!",
	DONE = "마침내, 마실만한게 나왔군.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "격식 있는 음료 도구야.",
	EMPTY = "쓸쓸하게도 음료가 하나도 없어.",
	BOILING_LONG = "나는 인내심을 길러야 해...",
	BOILING_SHORT = "곧 끝날거야.",
	DONE = "마실만한 게 나온 건지나 빌어야지.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WEBBER

STRINGS.CHARACTERS.WEBBER.DESCRIBE.WELL_DRILLING = "야호! 우물을 만들자!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WELL_DRILLING_ITEM = "우린 우물을 만들 좋은 자릴 찾을거야!"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.HOLE = "아~~ 거기 누구 계세요?"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_EMPTY = "내 장난감을 담아도 좋겠어."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_CLEAN = "마셔도 좋아."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_DIRTY = "양말 빤 물냄새가 나!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_SALTY = "바닷물은 마셔선 안되던가?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_ICE = "꽁!꽁!"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_TREE = "풀향기가 엄청나!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUG_TEA_TREE = "땅으로 보내줄께!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_SEED = "먹을 부분이 거의 없네."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_SEED_COOKED = "맛있을것 같지는 않은데?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_SEED_SAPLING = "오래오래 자유롭게 살렴."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEALEAVES = "아마도 찻잎의 일종인가봐."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEALEAVES_DRIED = "바싹 말랐어."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUG_CAFFEINBERRY = "땅으로 보내줄께!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAFFEINBERRY = "맛있어 보이진 않아."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAFFEINBERRY_BEAN = "이 냄새는 아주...어른스러운 냄새가 나"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "이것들은 날 웃기게 해."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.CUP = "컵이야!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CLEANWATER = "마셔도 좋아."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DIRTY = "양말 빤 물냄새가 나!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SALTY = "바닷물은 마셔선 안되던가?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GARBAGE = "새로운 시도는 언제나 즐거워!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FRUIT = "과일과 물을 한번에!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BERRIES_TEA = "시큼한데 맛있어."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.POMEGRANATE_TEA = "커다란 열매가 그대로 보여."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BANANA_TEA = "으으음,따듯하고 바나나향이 나."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FIG_TEA = "으으음, 정말 달콤한 향이야."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DRAGONFRUIT_TEA = "이제 더 맛있어 보여."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GLOWBERRY = "빛이 쏟아져 나오고 있어."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAFFEINBERRY_JUICE = "써."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.VEGGIE = "으으음,마셔야겠지?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CARROT_TEA = "막상 눈 앞에 있으니깐 마실까 고민되네?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CACTUS_TEA = "야호,물 맛이 어때!."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MULLED = "매울것 같은데?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GREENTEA = "떫을것 같아!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BLACKTEA = "우유가 있었으면 좋겠어!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BLACKTEA_ICED = "차가 시원해."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FUER = "또 다른 허브차인가봐!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MIXFLOWER = "꽃잎들이 춤추고 있어!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.HIBISCUS = "커다란 꽃이 그대로 보여."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CACTUSFLOWER = "나쁘지 않네!."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LOTUSFLOWER = "정말 예쁜 분홍색이야!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SUSHIBISCUS = "커다란 꽃이 그대로 보여."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPOILED_DRINK = "우웨엑!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SODA = "와!여기서 탄산음료를 다시보게 될줄은 꿈도 못 꿨는데!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.FRUITSODA = "탄산음료라니,정말 꿈만같아!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.LLSODA = "얼른 마시고 싶어!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COLA = "정말 그리웠어!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.COLAQUANTUM = "진짜 화려한 콜라다!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BEER = "어른들은 이런걸 어떻게 마시지?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.MEAD = "으으음....쓰고 시큼해."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WINE = "떫고 써."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.NOBLEWINE = "조금 더 달지만 여전히 써."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPARKLINGWINE = "마구 흔들어 보자!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.GLOWBERRYWINE = "화려하지만 술이잖아?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.KUMIS = "우유가 아니야?"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.WELL = "굳이 수영할 필요는 없을것 같아."

STRINGS.CHARACTERS.WEBBER.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "퍼올걸 가져오자!"
STRINGS.CHARACTERS.WEBBER.ACTIONFAIL.GIVE.WELL_BUSY = "더이상 바구니를 매달곳이 없어."

STRINGS.CHARACTERS.WEBBER.DESCRIBE.DESALINATOR = {
	EMPTY = "위커 선생님,이건 어떻게 작동하나요?",
	PURIFY = "물소리가 들려!",
	HASWATER = "이제 마셔도 되나봐!",
	BURNT = "누군가 불을 끄지 않고 놔둔게 틀림없어.",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BARREL = {
	GENERIC = "여기엔 물을 담나봐.",
	BURNT = "누군가 불을 끄지 않고 놔둔게 틀림없어.",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BREWERY = {
	GENERIC = "재료를 넣으면 다른 음료가 나와.",
	BURNT = "누군가 불을 끄지 않고 놔둔게 틀림없어.",
	FERMENTING_LONG = "그렇게 빨리 완성되진 않을거야.",
	FERMENTING_SHORT = "거의 다 됬어!",
	DONE = "이제 마셔보자!",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAMPKETTLE_ITEM = "생존 전문가가 된 기분이야."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAMPKETTLE = {
	GENERIC = "주전자만 뜨거워지고 있어.",
	BOILING_LONG = "미지근해.",
	BOILING_SHORY = "으으음,뜨끈뜨끈해!",
	DONE = "이제 마셔도 될것 같아!",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.KETTLE = {
	GENERIC = "재료를 넣으면 다른 음료가 나와.",
	BURNT = "S누군가 불을 끄지 않고 놔둔게 틀림없어.",
	BOILING_LONG = "그렇게 빨리 완성되진 않을거야.",
	BOILING_SHORT = "거의 다 됬어!",
	DONE = "음료를 마실 시간이야!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "맛난걸 만들어!",
	EMPTY = "에이,안에 아무것도 없네.",
	BOILING_LONG = "This is taking so loooong!",
	BOILING_SHORT = "곧 있으면 음료가 준비될 거야!",
	DONE = "으으음! 어서 마시자!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WENDY

STRINGS.CHARACTERS.WENDY.DESCRIBE.WELL_DRILLING = "대지와 싸우고 있어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WELL_DRILLING_ITEM = "우물을 만들 자리를 찾아야 할것 같아."

STRINGS.CHARACTERS.WENDY.DESCRIBE.HOLE = "깊은 심연속에 삼켜지는것 같아."

STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_EMPTY = "공허로 가득 차 있어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_CLEAN = "물로 가득해."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_DIRTY = "탁하고 나쁜냄새가 나."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_SALTY = "갈증만 갈망하게 되네."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_ICE = "내 심장처럼 꽁꽁 얼어버렸네."

STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_TREE = "향기로운 작은 나무야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.DUG_TEA_TREE = "죽은 그대로가 맘에 들지만, 땅으로 되돌려줘야 할것 같아."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_SEED = "겉만 번지르르 해."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_SEED_COOKED = "훨씬 보기 좋네."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_SEED_SAPLING = "나무가 곧 자랄거야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEALEAVES = "향긋한 찻잎이야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEALEAVES_DRIED = "찻잎이야.확실하게 죽었어."

STRINGS.CHARACTERS.WENDY.DESCRIBE.DUG_CAFFEINBERRY = "죽은 그대로가 맘에 들지만, 땅으로 되돌려줘야 할것 같아."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAFFEINBERRY = "이 식물은 타는듯한 죽음에서 양분을 얻어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAFFEINBERRY_BEAN = "자극적으로 보여"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "살고자 하는 의지가 콩으로부터 왔는지 누가 알았겠어."

STRINGS.CHARACTERS.WENDY.DESCRIBE.CUP = "여기에 담을만큼 흘릴 눈물도 남지 않았어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CLEANWATER = "깨끗한 물이야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.DIRTY = "탁하고 나쁜 냄새가 나."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SALTY = "갈증만 갈망하게 되네."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GARBAGE = "삶이 그렇듯, 끔찍하게 엉망이야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUIT = "새콤달콤한 과일이 담긴 차야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BERRIES_TEA = "시큼하면서도 달아."
STRINGS.CHARACTERS.WENDY.DESCRIBE.POMEGRANATE_TEA = "저승의 음료일까."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BANANA_TEA = "껍질채 넣은 바나나 음료야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.FIG_TEA = "안에 벌이 있었더라도 다 익사했겠지."
STRINGS.CHARACTERS.WENDY.DESCRIBE.DRAGONFRUIT_TEA = "용의 알이라고 하면 그럭저럭 납득이 될것 같기도 해, 이젠 죽었지만."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GLOWBERRY = "빛나는 음료야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAFFEINBERRY_JUICE = "어둡고 써."
STRINGS.CHARACTERS.WENDY.DESCRIBE.VEGGIE = "야채들이 담긴 차야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CARROT_TEA = "당근이 담긴 차야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CACTUS_TEA = "선인장을 갈아죽여서 만든 음료야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MULLED = "맵고 어두워."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GREENTEA = "녹차야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BLACKTEA = "홍챠야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BLACKTEA_ICED = "얼음 넣은 홍차야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.FUER = "잎들을 삶아 죽였어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MIXFLOWER = "그다지 의미부여 하고 싶지 않아."
STRINGS.CHARACTERS.WENDY.DESCRIBE.HIBISCUS = "꽃의 삶을 비참하게 끝냈어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CACTUSFLOWER = "그 아름다운 꽃은 이렇게 끝나버렸네."
STRINGS.CHARACTERS.WENDY.DESCRIBE.LOTUSFLOWER = "미녀는 일찍 죽는 법."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SUSHIBISCUS = "이걸 마시면 아비게일과 같은 세상을 볼 수 있을지도 몰라."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPOILED_DRINK = "죽음이 다 마셔버렸어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SODA = "목이 따끔거릴거야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUITSODA = "과일향 소다야"
STRINGS.CHARACTERS.WENDY.DESCRIBE.LLSODA = "너무 자주 마시면 달콤한 죽음이 찾아올거야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.COLA = "아비게일도 이걸 그리워 할텐데."
STRINGS.CHARACTERS.WENDY.DESCRIBE.COLAQUANTUM = "눈이 부실정도로 밝아."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEER = "마시면 서서히 죽음에 가까워진다는걸 사람들은 잘 모르지."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MEAD = "수 많은 벌들의 희생위에 만들었어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WINE = "피 처럼 붉어."
STRINGS.CHARACTERS.WENDY.DESCRIBE.NOBLEWINE = "그냥 와인보다 달고 밝아."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPARKLINGWINE = "파티에 어울리겠지, 내가 아니라."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GLOWBERRYWINE = "빛나는 와인이야."
STRINGS.CHARACTERS.WENDY.DESCRIBE.KUMIS = "이 술을 위해 얼마나 많은 아기동물들을 굶겼을까."

STRINGS.CHARACTERS.WENDY.DESCRIBE.WELL = "메아리가 들려."

STRINGS.CHARACTERS.WENDY.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "양동이를 가져와야 해."
STRINGS.CHARACTERS.WENDY.ACTIONFAIL.GIVE.WELL_BUSY = "기다려야 해."

STRINGS.CHARACTERS.WENDY.DESCRIBE.DESALINATOR = {
	EMPTY = "죽음에서 삶으로.",
	PURIFY = "정수중이야.",
	HASWATER = "정수가 끝났어.",
	BURNT = "바삭하게 태워졌어.",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.BARREL = {
	GENERIC = "물을 담는 나무통이야",
	BURNT = "바삭하게 태워졌어.",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.BREWERY = {
	GENERIC = "내 영혼만큼이나 허전해.",
	BURNT = "바삭하게 태워졌어.",
	FERMENTING_LONG = "무엇이 들어있던간에 아직 완벽하게 죽지 않았어.",
	FERMENTING_SHORT = "좀 더 발효 해야 해.",
	DONE = "이제 마실수 있어.",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.CAMPKETTLE_ITEM = "내가 이 가느다란 삶을 이어가길 원할때를 위해.."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAMPKETTLE = {
	GENERIC = "공허로 가득 차 있어",
	BOILING_LONG = "기다려야 해.",
	BOILING_SHORY = "좀 더 끓여야 해.",
	DONE = "이제 마실수 있어.",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.KETTLE = {
	GENERIC = "내 영혼만큼이나 허전해.",
	BURNT = "바삭하게 태워졌어.",
	BOILING_LONG = "무엇이 들어있던간에 아직 완벽하게 죽지 않았어.",
	BOILING_SHORT = "좀 더 끓여야 해.",
	DONE = "이제 마실수 있어.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "목마름이 내 작은 목를 물어뜯을 때를 위해...",
	EMPTY = "오직 공허만이 남은 갈증.",
	BOILING_LONG = "어쩌면 다 되기도 전에 탈수로 죽을지도.",
	BOILING_SHORT = "곧 완성될거야.",
	DONE = "또 다른 사소한 일이 끝났어..",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WICKERBOTTOM

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WELL_DRILLING = "우물을 파기 적당한 장소를 찾아야겠어."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WELL_DRILLING_ITEM = "아주 효율적이군!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HOLE = "물소리가 들리는걸 보니 재대로 팠구나."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_EMPTY = "나무로 만들어진 동이란다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_CLEAN = "급하다면 이대로 마셔야겠지."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_DIRTY = "살모넬라균이 득실하단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_SALTY = "오히러 탈수를 일으킬수 있어."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_ICE = "동이 째로 얼어버렸구나."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_TREE = "자그마한 동백나무의 일종인 차나무로구나."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_TEA_TREE = "성장을 위해 토양을 필요로 한단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_SEED = "차나무의 씨얏이란다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_SEED_COOKED = "심는쪽이 더 나았겠어."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_SEED_SAPLING = "치나무의 종자가 성장할 것이야."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEALEAVES = "찻잎중에서도 소엽종이란다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEALEAVES_DRIED = "홍차의 재료로 쓰일것이야."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_CAFFEINBERRY = "성장을 위해 토양을 필요로 한단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAFFEINBERRY = "커피속 식물이구나."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAFFEINBERRY_BEAN = "카페인 함량이 높단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "아아, 그 볶은 향이 정말 향긋하구나."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CUP = "컵 없이 입을 대고 마시는건 배려가 부족한 행동이지."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CLEANWATER = "이건 깨끗해."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DIRTY = "버리는게 낫겠어."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALTY = "오히러 탈수를 일으킬수 있어."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GARBAGE = "이런,안돼,안돼,안돼,이러면 안되는데."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRUIT = "조금 엉성한 과일들로 만들어도 좋단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BERRIES_TEA = "백량금 열매의 약리작용으로는 해열, 소염등이 있단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.POMEGRANATE_TEA = "천연 에스트로겐이 풍부하단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BANANA_TEA = "따뜻하게 마시는것도 나쁘지 않겠지."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FIG_TEA = "사족이지만 무화과는 이 열매가 꽃이란다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DRAGONFRUIT_TEA = "백육종은 가장 은은한 향을 낸단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GLOWBERRY = "본적 없는 음료구나, 놀라워!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAFFEINBERRY_JUICE = "나는 한잔의 커피와 함께 괜찮은 내용의 책을 읽는걸 좋아한단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VEGGIE = "몸에 좋은것들만 담았구나."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CARROT_TEA = "몸에도 좋고 맛도 좋아."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CACTUS_TEA = "섬유질이 풍부해서 변비에 좋단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MULLED = "뱅쇼라고도 하지,감기에 걸렸을때 만들어 마신단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GREENTEA = "너무 오래 우려서 탄닌이 지나치게 나오지 않게 하자꾸나."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BLACKTEA = "다도회를 열어야 겠구나."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BLACKTEA_ICED = "약간의 설탕과 레몬이 있으면 좋겠네."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FUER = "좋은 방법을 찾은것 같구나!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MIXFLOWER = "향기롭고 은은한 단맛을 낸단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HIBISCUS = "무궁화속 꽃을 차로 만든것이란다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CACTUSFLOWER = "백년초는 관절염에도 좋단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LOTUSFLOWER = "보고만 있어도 차분해지는것 같네."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUSHIBISCUS = "무궁화속 꽃을 차로 만든것이란다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOILED_DRINK = "유익균보다 유해균이 더 많아."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SODA = "탄산은 카보닐산 이라고도 한단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRUITSODA = "웰치스랑 비슷한 향이 나는구나."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LLSODA = "사실 과일쥬스가 당분함량이 더 높단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COLA = "막힌 변기를 이걸로 뚫어본적도 있었지."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COLAQUANTUM = "체렌코프 현상을 일으키고 있구나."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEER = "고대 이집트에도 맥주를 마셨단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MEAD = "오래 발효할수록 단맛이 줄어든단다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WINE = "한번 더 증류하면 브랜디가 되지."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NOBLEWINE = "곰팡이가 단맛의 원인이란다."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPARKLINGWINE = "마실거라면 흔들지 말자꾸나."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GLOWBERRYWINE = "완전히 새로운 종류의 와인이구나,놀라워!."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KUMIS = "사실 도수가 굉장히 낮단다."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WELL = "깨끗한 지하수를 퍼올릴수 있단다."

STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "물을 길을만한걸 가져와야지."
STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL.GIVE.WELL_BUSY = "기다리자꾸나."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DESALINATOR = {
	EMPTY = "바닷물을 마실수 있게 염분을 제거해 준단다.",
	PURIFY = "소금을 거르는중이야.",
	HASWATER = "이제 마셔도 되",
	BURNT = "이제 정말로 황량해.",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BARREL = {
	GENERIC = "물을 저장할수 있단다.",
	BURNT = "이제 정말로 황량해.",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BREWERY = {
	GENERIC = "이건 음료를 안 만들고 있는 때는 황량해 보여.",
	BURNT = "이제 정말로 황량해.",
	FERMENTING_LONG = "음료가 준비 되려면 아직 멀었어.",
	FERMENTING_SHORT = "거의 다 됬어!",
	DONE = "마실 시간!",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAMPKETTLE_ITEM = "야생의 수원에는 박테리아가 들끓지."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAMPKETTLE = {
	GENERIC = "비어 있단다.",
	BOILING_LONG = "지금 마시면 배탈난단다.",
	BOILING_SHORY = "충분히 가열해야해.",
	DONE = "이제 마셔도 좋아.",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KETTLE = {
	EMPTY = "이건 음료를 안 만들고 있는 때는 황량해 보여.",
	BURNT = "이제 정말로 황량해.",
	BOILING_LONG = "음료가 준비 되려면 아직 멀었어.",
	BOILING_SHORT = "거의 다 됬어!",
	DONE = "티 타임!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "어디서든 들고 다닐수 있겠구나.",
	EMPTY = "흠, 어쩌면 내가 뭘 해 볼수 있을지도.",
	BOILING_LONG = "인내는 미덕이라네.",
	BOILING_SHORT = "곧 끝날거야.",
	DONE = "풍부한 향이 나는군.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WILLOW

STRINGS.CHARACTERS.WILLOW.DESCRIBE.WELL_DRILLING = "그래,땅에게 본때를 보여줘!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WELL_DRILLING_ITEM = "우물 팔 곳을 찾아봐야 겠어."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.HOLE = "라이터를 떨어트리지 않게 조심해야겠아."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_EMPTY = "비어있는 양동이야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_CLEAN = "깨끗하네,아직은."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_DIRTY = "누가 이걸로 내 불을 꺼버리진 않겠지?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_SALTY = "바다에서 막 퍼왔어."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_ICE = "꽁 꽁 얼어버렸네."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_TREE = "태우면 향이 더 멀리까지 퍼지겠지?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUG_TEA_TREE = "왜 그래, 흙이 없어서 그래?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_SEED = "안녕,나무열매야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_SEED_COOKED = "이젠 어쨌거나 나무가 못 되겠구나."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_SEED_SAPLING = "곧 진짜 나무가 될수 있을거야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEALEAVES = "정말 향기로운 불쏘시개야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEALEAVES_DRIED = "불에 던져넣으면 향 연기가 피어오르겠지?"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUG_CAFFEINBERRY = "왜 그래, 흙이 없어서 그래?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAFFEINBERRY = "불꽃을 닮은게 너랑 친구가 될수 있겠다."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAFFEINBERRY_BEAN = "불을 써서 조리할수 있어."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "아아...이 아로마!"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.CUP = "맘 같아서는 심지와 밀랍으로 채우고 싶네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CLEANWATER = "깨끗하네,아직은."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DIRTY = "불을 써서 살균해야 겠어."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SALTY = "차라리 밀랍이 담겨져 있는게 도움이 되겠어."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GARBAGE = "어떻게 이럴 수가 있어?! 그냥 불로 끓이기만 하면 되는 게 전부잖아."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUIT = "향기로운 과일차 한잔!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BERRIES_TEA = "불에 익힌 베리지만,물 속에 있네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.POMEGRANATE_TEA = "불과 물과 과일의 환상적인 궁합이네!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BANANA_TEA = "향긋하네!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FIG_TEA = "불을 쓰면 물 속에 있어도 뭐든 맛있어지지."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DRAGONFRUIT_TEA = "이젠 완전히 물 처럼 변했잖아,실망이야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GLOWBERRY = "불처럼 빛을내는 물이라니, 완전 이상해."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAFFEINBERRY_JUICE = "갑자기 의욕이 생기는것 같아."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VEGGIE = "으,채소가 물 속에 한가득."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CARROT_TEA = "불에 익혔지만 물 속에 있고 채소야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CACTUS_TEA = "가시가 남아 있을까봐 두려워."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MULLED = "따듯한게 마음에 들어!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GREENTEA = "그래,물 속에 넣어도 향기롭네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BLACKTEA = "물에 넣어도 불을 쓰면 뭐, 그럭저럭."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BLACKTEA_ICED = "윽, 차갑잖아?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FUER = "불쏘시개를 왜 물에 넣은거야?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MIXFLOWER = "이제 좀 쓰임새를 찾은것 같네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.HIBISCUS = "마치 물속에 불꽃이 있는것 같네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CACTUSFLOWER = "그토록 원하는 물 속에서 죽었네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LOTUSFLOWER = "원래 물이랑 친한 꽃이잖아? 불로 삶았지만."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUSHIBISCUS = "마치 물속에 불꽃이 있는것 같네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPOILED_DRINK = "으윽.타지 않는 쓰레기야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SODA = "타는듯한 갈증에는 효과적이지."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUITSODA = "과일향이 나는 탄산음료야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LLSODA = "설탕을 너무 많이 넣은거 아니야?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COLA = "이건 차가운 편이 좋아."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COLAQUANTUM = "이건 내가 마셔야 해!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEER = "끓여서 스프로 만들어 마실래."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MEAD = "꿀로 만들었는데 그렇게 안 달콤하네."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WINE = "닭고기를 구해서 코코뱅으로 만드는게 낫겠어."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.NOBLEWINE = "이게 내가 좋아하는 와인이야."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPARKLINGWINE = "파티엔 샴페인에 캠프파이어도 필요하지."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GLOWBERRYWINE = "내가 꼭 마셔야 할 술이야!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.KUMIS = "살다살다 우유로 만든 술을 보네."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.WELL = "이제 누가 이 우물 물로 내 불을 끄진 않는지 봐야겠어."

STRINGS.CHARACTERS.WILLOW.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "맞다.물 양동이를 깜빡했네."
STRINGS.CHARACTERS.WILLOW.ACTIONFAIL.GIVE.WELL_BUSY = "이미 누가 쓰고있어."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DESALINATOR = {
	EMPTY = "불을 쓰는 방법이 난 좋은데.",
	PURIFY = "이 방법은 불도 안 쓰고 느리고...",
	HASWATER = "어디 한번 확인해보자.",
	BURNT = "적어도 그건 영광의 불길속에 있었어.",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BARREL = {
	GENERIC = "누가 여기서 물을 길어다 내 불들을 끄기 전에 내가 다 마셔버려야겠어.",
	BURNT = "적어도 그건 영광의 불길속에 있었어.",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BREWERY = {
	GENERIC = "불을 쓰지 않는 기구라는게 참 슬퍼",
	BURNT = "적어도 그건 영광의 불길속에 있었어.",
	FERMENTING_LONG = "불을 쓰면 더 빠르게 발효되지 않을까?",
	FERMENTING_SHORT = "슬프게도 불 없이도 완성이 거의 다 됬네.",
	DONE = "불 없이 만든 음료는 좀 미덥단 말이지",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAMPKETTLE_ITEM = "불로 정화하리라."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAMPKETTLE = {
	GENERIC = "불에게 일을 좀 줘야겠어.",
	BOILING_LONG = "그 불은 아직 할 일이 많이 남았어.",
	BOILING_SHORY = "불이 열심히 일하는 중 이야!",
	DONE = "불은 뭐든 낫게 만들지!",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.KETTLE = {
	EMPTY = "모든 음료는 불로 살균해야 해.",
	BURNT = "적어도 그건 영광의 불길속에 있었어.",
	BOILING_LONG = "그 불은 아직 할 일이 많이 남았어.",
	BOILING_SHORT = "불이 열심히 일하는 중 이야!",
	DONE = "불은 뭐든 낫게 만들지.음!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "이 멍청한걸 들고 다녀야해?",
	EMPTY = "멍청한 속 빈 주전자 같으니.",
	BOILING_LONG = "으으으,영원히 끝나지 않을것 같아!",
	BOILING_SHORT = "제발 불아,너가 할 일을 !",
	DONE = "좋았어. 이제 마시자!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WINONA

STRINGS.CHARACTERS.WINONA.DESCRIBE.WELL_DRILLING = "아주 편리하군!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.WELL_DRILLING_ITEM = "이 장치가 나 대신 굴착을 대신 해줄거야."

STRINGS.CHARACTERS.WINONA.DESCRIBE.HOLE = "정말 바닥이 보이지 않는군."

STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_EMPTY = "규격이 멋대로네.쓸만은 하겠지만."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_CLEAN = "물이 좀 새는것 같지만 괜찮겠지."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_DIRTY = "이 물 론 빨래도 못 하겠어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_SALTY = "얘는 기계로부터 멀리 해야겠어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_ICE = "꽝꽝 얼었군. 부수면 얼음은 얻을수 있겠어."

STRINGS.CHARACTERS.WINONA.DESCRIBE.TEA_TREE = "향기로운 이파리를 갖고있군,흥미롭네."
STRINGS.CHARACTERS.WINONA.DESCRIBE.DUG_TEA_TREE = "손은 더러워지겠지만 향이 남겠어,하하."
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEA_SEED = "먹을만한 부분이 거의 없네."
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEA_SEED_COOKED = "굽는다고 별로 달라지진 않는군."
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEA_SEED_SAPLING = "이 나무는 이제 뼈대를 세웠을 뿐이야."
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEALEAVES = "향긋하군,한번 물에 넣고 끓여봐야겠어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEALEAVES_DRIED = "이제 찻잎이 다 됬네"

STRINGS.CHARACTERS.WINONA.DESCRIBE.DUG_CAFFEINBERRY = "난 손 더럽히는 일이 좋아."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAFFEINBERRY = "일종의 콩 공장이로군."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAFFEINBERRY_BEAN = "이 향기는... 커피인가?"
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "갓 볶은 원두는 정말로 아로마가 풍부해."

STRINGS.CHARACTERS.WINONA.DESCRIBE.CUP = "일하고 난 뒤에 마시는 음료는 정말 각별하지."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CLEANWATER = "순수하게 물이야."
STRINGS.CHARACTERS.WINONA.DESCRIBE.DIRTY = "정말 급한게 아니라면..."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SALTY = "나는 기계가 아니지만 안 마시는게 좋겠어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.GARBAGE = "웩."
STRINGS.CHARACTERS.WINONA.DESCRIBE.FRUIT = "달고 비타민도 풍부해."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BERRIES_TEA = "새콤달콤하고 맛있겠네."
STRINGS.CHARACTERS.WINONA.DESCRIBE.POMEGRANATE_TEA = "정말 매력적인 향이로군."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BANANA_TEA = "바나나를 통째로 끓인다 해서 이상할건 없지."
STRINGS.CHARACTERS.WINONA.DESCRIBE.FIG_TEA = "조금 향이 독특하긴 하지만 달콤할것 같네."
STRINGS.CHARACTERS.WINONA.DESCRIBE.DRAGONFRUIT_TEA = "향이 은은하고 과하지 않은게, 확실히 고급 과일이네."
STRINGS.CHARACTERS.WINONA.DESCRIBE.GLOWBERRY = "열매도 빛을 내는데 음료라고 빛을 안 낼까."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAFFEINBERRY_JUICE = "인간성은 커피로 움직이는법."
STRINGS.CHARACTERS.WINONA.DESCRIBE.VEGGIE = "비타민이 정말 풍부하겠어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CARROT_TEA = "정말 효율적으로 가공해냈어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CACTUS_TEA = "알로에 쥬스라고 생각하면 되겠지?."
STRINGS.CHARACTERS.WINONA.DESCRIBE.MULLED = "몸이 아플때 이걸 마시고 푹자면 다시 일할수 있어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.GREENTEA = "목에 스며드는게 일품이야."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BLACKTEA = "설탕이 있었으면 좋겠군."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BLACKTEA_ICED = "일할때는 찬 음료가 마시고 싶은 법 이지."
STRINGS.CHARACTERS.WINONA.DESCRIBE.FUER = "이것도 차라고 할수 있지."
STRINGS.CHARACTERS.WINONA.DESCRIBE.MIXFLOWER = "정말 향기롭군."
STRINGS.CHARACTERS.WINONA.DESCRIBE.HIBISCUS = "미관상으로도 훌룡해."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CACTUSFLOWER = "꽤 아름다운데?"
STRINGS.CHARACTERS.WINONA.DESCRIBE.LOTUSFLOWER = "정말 아름다운 차군."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SUSHIBISCUS = "예쁜 꽃이 들어있기는 하는데,뭔가 이상하군."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SPOILED_DRINK = "1마일 정도 나랑 떨어져 있으면 좋겠어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SODA = "땀을 많이 흘리면 마시고 싶어지지."
STRINGS.CHARACTERS.WINONA.DESCRIBE.FRUITSODA = "정말 시원하고 맛있겠는데?"
STRINGS.CHARACTERS.WINONA.DESCRIBE.LLSODA = "격렬하게 일했다면 당분이 엄청 필요해."
STRINGS.CHARACTERS.WINONA.DESCRIBE.COLA = "설탕이 많이들었고, 카페인도 약간은 들어서 마음에 들어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.COLAQUANTUM = "신기하군, 빛을 내는 콜라라."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BEER = "일 끝난뒤의 맥주는 각별하지."
STRINGS.CHARACTERS.WINONA.DESCRIBE.MEAD = "이웃이 이런걸 잘 만들던데."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WINE = "나와 별로 만날 기회가 없는 술이야."
STRINGS.CHARACTERS.WINONA.DESCRIBE.NOBLEWINE = "음...달콤해라."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SPARKLINGWINE = "혹시나 배를 만들게 되면 한번 던져봐야겠어."
STRINGS.CHARACTERS.WINONA.DESCRIBE.GLOWBERRYWINE = "술이 빛을 내는것도 이상할건 없지,안그래?"
STRINGS.CHARACTERS.WINONA.DESCRIBE.KUMIS = "이것도 술인가?"

STRINGS.CHARACTERS.WINONA.DESCRIBE.WELL = "도르래가 정말 잘 돌아가는군!"

STRINGS.CHARACTERS.WINONA.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "양동이 만드는게 뭐 어렵겠어?"
STRINGS.CHARACTERS.WINONA.ACTIONFAIL.GIVE.WELL_BUSY = "두개까지 들어가지는 않아"

STRINGS.CHARACTERS.WINONA.DESCRIBE.DESALINATOR = {
	EMPTY = "음...완벽해!",
	PURIFY = "잘 작동하고 있어.",
	HASWATER = "잘 작동했는지 마셔보자.",
	BURNT = "괜찮아,하나 더 조립하지 뭐.",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.BARREL = {
	GENERIC = "이것도 수제야.",
	BURNT = "물이 충분히 안 들어있었나 보네?",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.BREWERY = {
	GENERIC = "이렇게 하면 음료가 발효될 환경이 조성될거야.",
	BURNT = "다들 연골 좋아하잖아,그치?",
	FERMENTING_LONG = "좀 만 기다리자.",
	FERMENTING_SHORT = "거의!",
	DONE = "음료를 마십시다!",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.CAMPKETTLE_ITEM = "물을 살균하는 가장 확실한 방법중 하나지."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAMPKETTLE = {
	GENERIC = "정작 중요한 물은 안 들어있네.",
	BOILING_LONG = "아직 미지근해.",
	BOILING_SHORY = "좀 더 끓이자.",
	DONE = "이제 마셔도 될 것 같아.",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.KETTLE = {
	EMPTY = "내가 커피를 잘 타는데 말이야.",
	BURNT = "다들 연골 좋아하잖아,그치?",
	BOILING_LONG = "좀 만 기다리자.",
	BOILING_SHORT = "거의!",
	DONE = "음료를 마십시다!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "이 고급진 주전자를 어디든지 들고 다닐수 있지.",
	EMPTY = "재료를 조금 넣었으면 좋겠는걸?.",
	BOILING_LONG = "좋은 작품은 시간이 오래 걸리는 법.",
	BOILING_SHORT = "이 작업은 깔끔하게 완료될거야!",
	DONE = "그렇게 호들갑 떨 만한 가치가 있는지 보자.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WOLFGANG

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WELL_DRILLING = "강력하게 일하고 있다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WELL_DRILLING_ITEM = "볼프강을 위한 우물을 팔거다!"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.HOLE = "볼프강 구멍 안 보기 싫다!"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_EMPTY = "빈 양동이이다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_CLEAN = "내 팔 근육도 비쳐진다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_DIRTY = "구정물이 담긴 양동이다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_SALTY = "바다에서 막 퍼왔다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_ICE = "볼프강이 양동이를 부숴서 얼음을 꺼내줄수 있다!"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_TREE = "나무에서 향기가 퍼지고 있어."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUG_TEA_TREE = "춥고 외로워."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_SEED = "커다란 씨앗들도 내 손엔 부숴지지!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_SEED_COOKED = "나무열매에서 나무를 지웠다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_SEED_SAPLING = "정말 연약해 보이네."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEALEAVES = "냄새 좋은 이파리다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEALEAVES_DRIED = "좋은 냄새가 볼프강만큼 강해졌다."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUG_CAFFEINBERRY = "춥고 외로워"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAFFEINBERRY = "커피덤불은 힘 쌔고 자랑스럽다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAFFEINBERRY_BEAN = "작은 콩이 볼프강에게 힘을 준다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "쓴 콩이다!!"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CUP = "연약한 컵이다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CLEANWATER = "깨끗하다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DIRTY = "구정물이다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SALTY = "바다에서 막 퍼왔다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GARBAGE = "마시기 나쁘진 않지만, 좋지도 않다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUIT = "비타민 보충제로군."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BERRIES_TEA = "정말 맛있겠다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.POMEGRANATE_TEA = "마시면 똑똑해지나?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BANANA_TEA = "원숭이 차다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FIG_TEA = "달콤한 과일 차다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DRAGONFRUIT_TEA = "이젠 웃기는 색을 띈다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GLOWBERRY = "빛나는 음료수다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAFFEINBERRY_JUICE = "볼프강처럼 강하다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VEGGIE = "식이섬유 보충제다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CARROT_TEA = "이건 뭐지?."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CACTUS_TEA = "녹색 고기의 피다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MULLED = "볼프강은 이런거 전혀 이해 못하겠다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GREENTEA = "향기나는 물이다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BLACKTEA = "원한있는 사람이 있지 않지 조심해야 해..."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BLACKTEA_ICED = "차갑다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FUER = "시금치 차다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MIXFLOWER = "냄새도 좋고 예쁘고 물도 마실수 있다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.HIBISCUS = "붉고 예쁘다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CACTUSFLOWER = "녹색고기의 피와 심장이다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LOTUSFLOWER = "연못의 꽃이 다시 물로 돌아갔다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUSHIBISCUS = "붉고 예쁘다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPOILED_DRINK = "구역질 나는 물이야!."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SODA = "차가운데 부글부글 끓고있어."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUITSODA = "달콤하고 시원해!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LLSODA = "엄청나게 달다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COLA = "볼프강은 이거 너무 많이 마실까봐 걱정된다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COLAQUANTUM = "이상한거 안 들었길 바래."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEER = "볼프강은 뱃살같은거 걱정 안된다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MEAD = "꿀로 만든 보드카다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WINE = "볼프강도 와인 즐길줄 안다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.NOBLEWINE = "볼프강은 드라이 한거 좋아한다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPARKLINGWINE = "볼프강은 샴페인 터트리는거 자신있다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GLOWBERRYWINE = "힘쎄고 강한 술이다!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KUMIS = "우유에 보드카 더 타고 싶다!"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WELL = "볼프강이 힘 약한 친구 대신 물 길어줄수 있다!"

STRINGS.CHARACTERS.WOLFGANG.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "물을 담글 용기가 먼저다."
STRINGS.CHARACTERS.WOLFGANG.ACTIONFAIL.GIVE.WELL_BUSY = "두 개 까진 안 들어간다."

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DESALINATOR = {
	EMPTY = "바닷물에서 소금 찢는다!",
	PURIFY = "기계가 운동하고 있어.",
	HASWATER = "소금 찢었다.",
	BURNT = "물이 운동을 덜 했어.",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BARREL = {
	GENERIC = "안에 물 넣는다!",
	BURNT = "물이 운동을 덜 했어.",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BREWERY = {
	GENERIC = "술 만드는 기계다.",
	BURNT = "이제 술 못 마셔?",
	FERMENTING_LONG = "기계가 일하는동안 볼프강은 운동 할 수 있다.",
	FERMENTING_SHORT = "벌써 술 냄새가 난다!",
	DONE = "무슨 술이 나왔을까?",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAMPKETTLE_ITEM = "돌로 된 주전자 충분히 무겁다."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAMPKETTLE = {
	GENERIC = "볼프강이 친구들을 위해 물 구해올수 있다!",
	BOILING_LONG = "물을 끓이는 동안 볼프강은 운동 할 수 있다.",
	BOILING_SHORY = "펄펄 끓고 있다!",
	DONE = "앗 뜨뜨",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KETTLE = {
	EMPTY = "볼프강이 친구들을 위해 재료 채집해와야 겠어!",
	BURNT = "물이 운동을 덜 했어.",
	BOILING_LONG = "주전자가 음료를 만드는 동안 볼프강은 운동 할 수 있다.",
	BOILING_SHORT = "거의 다 됬어.",
	DONE = "마실 시간이다!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "볼프강이 음료를 놓을 테이블을 정리해줘야 겠어.",
	EMPTY = "볼프강이 친구들을 위해 재료 채집해와야 겠어!",
	BOILING_LONG = "주전자가 음료를 만드는 동안 볼프강은 운동 할 수 있다.",
	BOILING_SHORT = "벌써 좋은 냄새가 난다!",
	DONE = "마실 시간이다!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WOODIE

STRINGS.CHARACTERS.WOODIE.DESCRIBE.WELL_DRILLING = "일을 제대로 하고 있는 모양이군."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WELL_DRILLING_ITEM = "루시,어디에 우물을 파는게 좋을까?"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.HOLE = "어두컴컴해라."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_EMPTY = "나무 참 편하지?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_CLEAN = "물 한 바가지로군."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_DIRTY = "다 썩어가는것 같은데?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_SALTY = "음...짜!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_ICE = "이거 빠지긴 하나?"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_TREE = "공작재료로는 별로야."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUG_TEA_TREE = "조경 좀 꾸며볼 시간이다."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_SEED = "키워서 베어버려야겠어."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_SEED_COOKED = "나무를 그냥 버렸어."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_SEED_SAPLING = "나무가 나온다!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEALEAVES = "잎은 쓸만해 보이네."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEALEAVES_DRIED = "뜨거운 물 구해와,어서."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUG_CAFFEINBERRY = "조경 좀 꾸며볼 시간이다."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAFFEINBERRY = "커피 콩!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAFFEINBERRY_BEAN = "내가 볶아볼께."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "캐나다인은 커피를 좋아하지."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.CUP = "커피 좀 마시구 싶구만!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CLEANWATER = "이야 물!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DIRTY = "다 썩어가는것 같은데?."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SALTY = "음...짜!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GARBAGE = "이런, 완전 망했잖아?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FRUIT = "시럽도 좀 넣었으면 좋겠는걸?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BERRIES_TEA = "물로 양을 늘렸네,나쁘진 않은 생각이야."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.POMEGRANATE_TEA = "너무 고급져서 내가 이해를 못하겠네."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BANANA_TEA = "바나나가 어떻게 형체를 유지하고 있는거지?."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FIG_TEA = "정말 무쟈게 달구만."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DRAGONFRUIT_TEA = "완전 곤죽을 내놨네."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GLOWBERRY = "이야,여전히 빛을 내고 있네 하하."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAFFEINBERRY_JUICE = "정말 잘 했어!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VEGGIE = "몸에는 좋겠구먼."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CARROT_TEA = "토끼들도 차를 마시나?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CACTUS_TEA = "선인장을 짜낸거야?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MULLED = "근육통에 좋지."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GREENTEA = "갓 밴 나무향이 나네!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BLACKTEA = "이거 홍차야?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BLACKTEA_ICED = "차가우니 좋구만."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FUER = "삶은 시금치 냄새 비슷한것 같기도 하구먼."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MIXFLOWER = "꽃이 있으니 시럽도 있으면 더 좋지 않을까?."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.HIBISCUS = "예쁘긴 하는데 배는 안 부르겠어."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CACTUSFLOWER = "오유소스 지역의 명물 같구먼."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LOTUSFLOWER = "정말 예쁜 분홍색이야."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUSHIBISCUS = "이 꽃차 정말 예쁘지 않니,루시?."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPOILED_DRINK = "이런,썩었잖아!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SODA = "정말 시원하겠는데."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FRUITSODA = "맛있네!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LLSODA = "시원하고 좋네,그렇지 루시?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COLA = "이야,이걸 다시보니 좋네!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COLAQUANTUM = "정말 이상하고 놀랍구먼!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEER = "차갑든 따듯하든 내가 마셔버릴거야."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MEAD = "시럽을 만들러다 실패한건가?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WINE = "캐나다도 와인이 맛있거든?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.NOBLEWINE = "스위트하네!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPARKLINGWINE = "흔들자 흔들어!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GLOWBERRYWINE = "이야, 완전히 새로운 와인이야!."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.KUMIS = "완전 처음보는 음료구먼."

STRINGS.CHARACTERS.WOODIE.DESCRIBE.WELL = "이러니 완전 시골같구먼."

STRINGS.CHARACTERS.WOODIE.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "퍼올거 가져와!"
STRINGS.CHARACTERS.WOODIE.ACTIONFAIL.GIVE.WELL_BUSY = "빨리 빨리!"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DESALINATOR = {
	EMPTY = "좋아,바닷물을 넣어보자구.",
	PURIFY = "열심히 일하는군!",
	HASWATER = "마셔도 되나?",
	BURNT = "이게 어쩌다 탄거지?",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BARREL = {
	GENERIC = "이 오크통 아직 살아있는것 같은데?",
	BURNT = "정말 애석한 일이야.",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BREWERY = {
	GENERIC = "정말 기대 되는군!",
	BURNT = "이게 어쩌다 탄거지?",
	FERMENTING_LONG = "오래 걸릴거야.",
	FERMENTING_SHORT = "술 마시는게 기대 되,루시.",
	DONE = "뭐가 나왔을까!",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAMPKETTLE_ITEM = "배탈나면 나무도 못 베게 되!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAMPKETTLE = {
	GENERIC = "적어도 장작 걱정은 안해도 되겠지.",
	BOILING_LONG = "오래 걸릴거야.",
	BOILING_SHORY = "펄펄 끓는다!",
	DONE = "따뜻한 물!",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.KETTLE = {
	EMPTY = "저렇게 텅 빈 상태로 놔두면 낭비 같은데.",
	BURNT = "바삭하게 타버렸군.",
	BOILING_LONG = "오래 걸릴거야.",
	BOILING_SHORT = "얼마 안남았어,루시.",
	DONE = "뭐가 나왔을까!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "분명 캠프에 좋은 냄새가 나겠지",
	EMPTY = "저렇게 텅 빈 상태로 놔두면 낭비 같은데.",
	BOILING_LONG = "나무나 하고 와야겠군.",
	BOILING_SHORT = "벌써부터 좋은 냄새가 나네.",
	DONE = "뭐가 나왔을까!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WORMWOOD

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WELL_DRILLING = "땅 부수고 물 찾고있어"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WELL_DRILLING_ITEM = "커다란 물 줄기 찾아야 해"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.HOLE = "축축한 구멍"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_EMPTY = "뭐든 담아"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_CLEAN = "물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_DIRTY = "아픈 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_SALTY = "예민한 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_ICE = "차가워, 단단해"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEA_TREE = "매력적인 친구"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DUG_TEA_TREE = "흙 필요해"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEA_SEED = "푸등푸등해!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEA_SEED_COOKED = "이제 먹는거야."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEA_SEED_SAPLING = "무럭무럭 자라라!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEALEAVES = "친구야 향기로운 친구."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEALEAVES_DRIED = "바삭해"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DUG_CAFFEINBERRY = "흙 필요해"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAFFEINBERRY = "주우움베리 친구"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAFFEINBERRY_BEAN = "주우움베리!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "향 좋아"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CUP = "텅텅 비었어"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CLEANWATER = "믈"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DIRTY = "아픈 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SALTY = "예민한 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.GARBAGE = "후루룩"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.FRUIT = "과일 파티!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BERRIES_TEA = "호로로록"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.POMEGRANATE_TEA = "씨앗 호로록"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BANANA_TEA = "달콤 친구 따듯한 물 "
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.FIG_TEA = "달콤 호로록"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DRAGONFRUIT_TEA = "으으음!!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.GLOWBERRY = "빛나는 호로록"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAFFEINBERRY_JUICE = "휘이!!!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.VEGGIE = "흙 흙"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CARROT_TEA = "주황 친구 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CACTUS_TEA = "아야한 친구 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MULLED = "으음...?"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.GREENTEA = "향기 친구 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BLACKTEA = "향나는 갈색 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BLACKTEA_ICED = "차가워!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.FUER = "지하 친구 물."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MIXFLOWER = "냄새 좋아"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.HIBISCUS = "냄새 짱 좋아."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CACTUSFLOWER = "아야한 친구 예쁜 물."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.LOTUSFLOWER = "진흙 예쁜 친구 물."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUSHIBISCUS = "냄새 짱 좋아."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SPOILED_DRINK = "냄새 좋아?"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SODA = "따끔따끔"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.FRUITSODA = "새콤달콤 따끔따끔"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.LLSODA = "달달 따끔따끔."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.COLA = "검은색 따끔따끔."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.COLAQUANTUM = "빛나는 따끔따끔"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BEER = "이상한 냄새"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MEAD = "이상한 꿀 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WINE = "이상한 붉은 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.NOBLEWINE = "이상하고 달달 물"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SPARKLINGWINE = "이상하고 따끔따끔"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.GLOWBERRYWINE = "이상하고 빛나는 물."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.KUMIS = "이상한 하얀 물"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WELL = "물 푸는 곳"

STRINGS.CHARACTERS.WORMWOOD.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "물 못 푼다"
STRINGS.CHARACTERS.WORMWOOD.ACTIONFAIL.GIVE.WELL_BUSY = "물 푸고 있다"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DESALINATOR = {
	EMPTY = "물 달래는 곳",
	PURIFY = "물 달래고 있다",
	HASWATER = "물 순해졌다",
	BURNT = "히잉",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BARREL = {
	GENERIC = "물 담아",
	BURNT = "없어졌어",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BREWERY = {
	GENERIC = "이상한 물 만든다",
	BURNT = "불이 해쳤어",
	FERMENTING_LONG = "오래 걸려",
	FERMENTING_SHORT = "곧 끝나",
	DONE = "뭔가 나왔다",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAMPKETTLE_ITEM = "물 담고 끓여"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAMPKETTLE = {
	GENERIC = "텅 텅",
	BOILING_LONG = "오래 걸려",
	BOILING_SHORY = "곧 끝나",
	DONE = "앗 뜨뜨",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.KETTLE = {
	EMPTY = "물 바꿔줘",
	BURNT = "불이 전부 아프게 해",
	BOILING_LONG = "오래 걸려",
	BOILING_SHORT = "곧 끝나",
	DONE = "끝!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "마시는거 만들어",
	EMPTY = "비었어...",
	BOILING_LONG = "오래 걸려",
	BOILING_SHORT = "곧 끝나",
	DONE = "끝!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WORTOX

STRINGS.CHARACTERS.WORTOX.DESCRIBE.WELL_DRILLING = "나 대신 일 해라 기계야.ㅔ="
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WELL_DRILLING_ITEM = "일만 하고 안 놀면 임프는 불행해"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.HOLE = "심연을 깊게 들여다 보면 심연도 우리를..."

STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_EMPTY = "물을 담아두는 양동이야."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_CLEAN = "난 물이 그렇게 많이 필요하지 않아."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_DIRTY = "이건 조금 역겹군."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_SALTY = "워이~난 마시지 않을거야."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_ICE = "얼음을 저장하고 있는건가?"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEA_TREE = "향이나면 나무들한데 인기가 있을거라 생각하나 보네,안타깝다."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.DUG_TEA_TREE = "흙 없는 덤불은 물 없는 물고기나 마찬가지지."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEA_SEED = "정말 이기적인 열매군!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEA_SEED_COOKED = "이건 진짜로 먹을게 없군."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEA_SEED_SAPLING = "너 자라는 방법을 아는구나!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEALEAVES = "그 매력은 내가 취하도록 하지."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEALEAVES_DRIED = "향기 바사삭!"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.DUG_CAFFEINBERRY = "흙 없는 덤불은 물 없는 물고기나 마찬가지지."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAFFEINBERRY = "이곳에 없는 힘이 느껴지는것 같은데? 흐음."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAFFEINBERRY_BEAN = "그 이질적인 힘이 이 열매에서 느껴지는것 같군."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "그 이질적인 열매를 불태웠지."

STRINGS.CHARACTERS.WORTOX.DESCRIBE.CUP = "나에겐 딱 하나의 컵이면 충분하지."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CLEANWATER = "한잔의 마실수 있는 물이야."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.DIRTY = "이건 조금 역겹군."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SALTY = "워이~난 마시지 않을거야."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.GARBAGE = "흐유유~역겹기도 해라."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.FRUIT = "필멸자들은 과일을 참 좋아한단 말이지."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BERRIES_TEA = "이러면 더 오래가나?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.POMEGRANATE_TEA = "스틱스 강물이라도 담았나 보네."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BANANA_TEA = "이건 또 다른 형태의 바나나로군."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.FIG_TEA = "사양할게."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.DRAGONFRUIT_TEA = "용의 피는 하얀색이였어,흐유유~"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.GLOWBERRY = "이젠 음료도 빛나는구먼."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAFFEINBERRY_JUICE = "필멸자들은 이 쓴 걸 왜 그렇게 좋아하는거지?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.VEGGIE = "필멸자들 사이에서도 호불호가 갈리는것 같더라고."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CARROT_TEA = "비 임프들이 좋아하겠는데?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CACTUS_TEA = "가시를 전부 갈아 없엤다고 해서 마시진 않을거야."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.MULLED = "일종의 탕약인가?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.GREENTEA = "향기로운 풀물이로구먼."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BLACKTEA = "흐유유~참 향기롭네"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BLACKTEA_ICED = "정말 참신한 생각이야."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.FUER = "그 보라빛 잎을 삶아 죽였지."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.MIXFLOWER = "꽃잎들의 물 속에서 휘날리는걸 봐봐,이미 죽었지만."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.HIBISCUS = "정말 아름답기도 해라!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CACTUSFLOWER = "꽃으로 장식했네? 그래도 마시진 않을거지만."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.LOTUSFLOWER = "내 자신을 등불로 삼아라, 내 맘대로 하라는거지."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUSHIBISCUS = "정말 아름답...잠깐."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SPOILED_DRINK = "으 이런,으 더러워,더러운 액체잖아."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SODA = "필멸자들은 진짜 이상한걸 만들어 마시기도 하는군."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.FRUITSODA = "과일을 참신한 음료로 만들었네!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.LLSODA = "필멸자들은 진짜 이상한걸 만들어 마시기도 하는군."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.COLA = "필멸자들이 좋아하는 또 다른 구정물이야."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.COLAQUANTUM = "이상한데다가 빛까지 나네."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BEER = "필멸자들은 머리가 아프고 헛소리를 하는걸 즐기나?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.MEAD = "꿀벌들의 노력이 이상한걸로 재탄생 했네."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WINE = "정말 이상한 피로군."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.NOBLEWINE = "사양할게."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SPARKLINGWINE = "이상하고 이상해라 흐유유."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.GLOWBERRYWINE = "이상한데다가 빛까지 나네."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.KUMIS = "이러면 좀 오래가나?"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.WELL = "동전이라도 한번 던져볼까!"

STRINGS.CHARACTERS.WORTOX.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "내 소지품에 동전이 있었던가."
STRINGS.CHARACTERS.WORTOX.ACTIONFAIL.GIVE.WELL_BUSY = "일을 방해하는건 좋은 생각이 아니야."

STRINGS.CHARACTERS.WORTOX.DESCRIBE.DESALINATOR = {
	EMPTY = "필멸자들도 쓸만한 생각을 하는군.",
	PURIFY = "작은 폭포로구먼.",
	HASWATER = "내 물이 거기에 있나?",
	BURNT = "뭐,재미는 있었어.",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.BARREL = {
	GENERIC = "영혼도 여기에 담을수 있으면 좋을텐데.",
	BURNT = "우습기도 해라.",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.BREWERY = {
	GENERIC = "필멸자들이 음식으로 장난을 치나 보네.",
	BURNT = "뭐,재미는 있었어.",
	FERMENTING_LONG = "다른 장난 좀 치고 와 볼까.",
	FERMENTING_SHORT = "오래 걸리지 않을거야.",
	DONE = "뭐가 나왔을까? 흐음...",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAMPKETTLE_ITEM = "그 뭐 임프들도 물을 그냥 마시면 배가 아플수도 있지."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAMPKETTLE = {
	GENERIC = "텅 비어있네",
	BOILING_LONG = "다른 장난 좀 치고 와 볼까.",
	BOILING_SHORY = "오래 걸리지 않을거야.",
	DONE = "후 후 불어서 마셔볼까!",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.KETTLE = {
	EMPTY = "텅 비어있네",
	BURNT = "우습기도 해라.",
	BOILING_LONG = "다른 장난 좀 치고 와 볼까.",
	BOILING_SHORT = "오래 걸리지 않을거야.",
	DONE = "뭐가 나왔을까? 흐음...",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "음료에 정말 정성을 쏟는구먼.",
	EMPTY = "음료가 전부 귀신같히 사라졌어",
	BOILING_LONG = "다른 장난 좀 치고 와 볼까.",
	BOILING_SHORT = "보글보글",
	DONE = "우리 요리사 친구가 뭘 만들었는지 한번 볼까!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WURT

STRINGS.CHARACTERS.WURT.DESCRIBE.WELL_DRILLING = "바위랑 싸워!"

STRINGS.CHARACTERS.WURT.DESCRIBE.WELL_DRILLING_ITEM = "매끈이들이'우물'을 만들때 쓰는 물건이야."

STRINGS.CHARACTERS.WURT.DESCRIBE.HOLE = "아래에 물이 있지만 보기만 해야해 -뻐끔"

STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_EMPTY = "이걸로 물 퍼올수 있어."
STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_CLEAN = "깨끄탄 물이야."
STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_DIRTY = "집 가튼 냄새가 나."
STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_SALTY = "피부에 별로 안조아."
STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_ICE = "너무 차가워."

STRINGS.CHARACTERS.WURT.DESCRIBE.TEA_TREE = "책에서 본적 있어, 차라는 거슬 만들수 있대!"
STRINGS.CHARACTERS.WURT.DESCRIBE.DUG_TEA_TREE = "너 나랑 가자,뽀륵"
STRINGS.CHARACTERS.WURT.DESCRIBE.TEA_SEED = "작은나무 씨앗!"
STRINGS.CHARACTERS.WURT.DESCRIBE.TEA_SEED_COOKED = "먹을게 없어..."
STRINGS.CHARACTERS.WURT.DESCRIBE.TEA_SEED_SAPLING = "크게 자라라!"
STRINGS.CHARACTERS.WURT.DESCRIBE.TEALEAVES = "어인은 이런거에 관심 없어, 난 관심 있어."
STRINGS.CHARACTERS.WURT.DESCRIBE.TEALEAVES_DRIED = "엄청 향기나! 뻐끔."

STRINGS.CHARACTERS.WURT.DESCRIBE.DUG_CAFFEINBERRY = "너 나랑 가자,뽀륵"
STRINGS.CHARACTERS.WURT.DESCRIBE.CAFFEINBERRY = "열매가 써."
STRINGS.CHARACTERS.WURT.DESCRIBE.CAFFEINBERRY_BEAN = "간식은 못 되."
STRINGS.CHARACTERS.WURT.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "여전히 써."

STRINGS.CHARACTERS.WURT.DESCRIBE.CUP = "음료를 담아,뽀륵."
STRINGS.CHARACTERS.WURT.DESCRIBE.CLEANWATER = "어인은 항상 물이 필요해, 뽀르륵."
STRINGS.CHARACTERS.WURT.DESCRIBE.DIRTY = "집 가튼 냄새가 나."
STRINGS.CHARACTERS.WURT.DESCRIBE.SALTY = "마셔서 안된다고 배워써 뽀륵..."
STRINGS.CHARACTERS.WURT.DESCRIBE.GARBAGE = "보통 질척한 거 좋아하지만..."
STRINGS.CHARACTERS.WURT.DESCRIBE.FRUIT = "과일이 한 가득!"
STRINGS.CHARACTERS.WURT.DESCRIBE.BERRIES_TEA = "간식이 먹기 쉬어져써."
STRINGS.CHARACTERS.WURT.DESCRIBE.POMEGRANATE_TEA = "이제 먹기 쉬어."
STRINGS.CHARACTERS.WURT.DESCRIBE.BANANA_TEA = "달콤 걸쭉해,뽀르륵."
STRINGS.CHARACTERS.WURT.DESCRIBE.FIG_TEA = "으으음, 정말 달콤해!"
STRINGS.CHARACTERS.WURT.DESCRIBE.DRAGONFRUIT_TEA = "아무 맛도 안나...?"
STRINGS.CHARACTERS.WURT.DESCRIBE.GLOWBERRY = "우와,집을 이 음료로 채워보고 싶어!"
STRINGS.CHARACTERS.WURT.DESCRIBE.CAFFEINBERRY_JUICE = "엄청 써!"
STRINGS.CHARACTERS.WURT.DESCRIBE.VEGGIE = "맛있어!"
STRINGS.CHARACTERS.WURT.DESCRIBE.CARROT_TEA = "맛있는데 먹기도 편해."
STRINGS.CHARACTERS.WURT.DESCRIBE.CACTUS_TEA = "가시가 이제 없나?"
STRINGS.CHARACTERS.WURT.DESCRIBE.MULLED = "매끈이들이 아플때 마시래,뽀륵."
STRINGS.CHARACTERS.WURT.DESCRIBE.GREENTEA = "향기로워!"
STRINGS.CHARACTERS.WURT.DESCRIBE.BLACKTEA = "이게 책에 적혀 있는 '차'인가봐."
STRINGS.CHARACTERS.WURT.DESCRIBE.BLACKTEA_ICED = "책에 얼음을 넣은건 못봐써."
STRINGS.CHARACTERS.WURT.DESCRIBE.FUER = "이것도 '치'인가봐!"
STRINGS.CHARACTERS.WURT.DESCRIBE.MIXFLOWER = "매끈이들은 이 음료가 예쁜가봐."
STRINGS.CHARACTERS.WURT.DESCRIBE.HIBISCUS = "정말 커다랗고 못생긴 꽃이 드러이써."
STRINGS.CHARACTERS.WURT.DESCRIBE.CACTUSFLOWER = "별로 매력 업서."
STRINGS.CHARACTERS.WURT.DESCRIBE.LOTUSFLOWER = "집 안에 온드한 향이 나."
STRINGS.CHARACTERS.WURT.DESCRIBE.SUSHIBISCUS = "정말 커다랗고 못생긴 꽃이 드러이써."
STRINGS.CHARACTERS.WURT.DESCRIBE.SPOILED_DRINK = "이거 아직 마셔도 괜찮나?."
STRINGS.CHARACTERS.WURT.DESCRIBE.SODA = "매끈이들이 재밌는 물 만드러써!"
STRINGS.CHARACTERS.WURT.DESCRIBE.FRUITSODA = "정말 재밌고 마시써!"
STRINGS.CHARACTERS.WURT.DESCRIBE.LLSODA = "엄청 달고 신나!"
STRINGS.CHARACTERS.WURT.DESCRIBE.COLA = "이상하게 거머,하지만 달고 마시쩌."
STRINGS.CHARACTERS.WURT.DESCRIBE.COLAQUANTUM = "꾸르륵,이거 머야?"
STRINGS.CHARACTERS.WURT.DESCRIBE.BEER = "워트는 쓴거 안 좋아해 꾸륵."
STRINGS.CHARACTERS.WURT.DESCRIBE.MEAD = "벌 꿀은 어디로 가써?"
STRINGS.CHARACTERS.WURT.DESCRIBE.WINE = "원래 과일이 훨씨인 나아 꾸륵.."
STRINGS.CHARACTERS.WURT.DESCRIBE.NOBLEWINE = "이상한 냄새만 안나면 조켔서."
STRINGS.CHARACTERS.WURT.DESCRIBE.SPARKLINGWINE = "이상한 향기가 나, 그래도 재미써."
STRINGS.CHARACTERS.WURT.DESCRIBE.GLOWBERRYWINE = "빛나서 좋은데 워트는 마시고 싶지 않아."
STRINGS.CHARACTERS.WURT.DESCRIBE.KUMIS = "꾸륵,우유에서 이상한 냄새 나."

STRINGS.CHARACTERS.WURT.DESCRIBE.WELL = "매끈이들이 물을 여기서 얻어."

STRINGS.CHARACTERS.WURT.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "내 손으론 닿지 않아 꾸륵."
STRINGS.CHARACTERS.WURT.ACTIONFAIL.GIVE.WELL_BUSY = "두개나 들어가지 않아."

STRINGS.CHARACTERS.WURT.DESCRIBE.DESALINATOR = {
	EMPTY = "바닷물을 넣으래써.",
	PURIFY = "워트는 기다릴 수 이써.",
	HASWATER = "이제 마셔도 되?",
	BURNT = "물 소게 있었으면 그럴 일도 업섰을거야.뻐끔",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.BARREL = {
	GENERIC = "물이 없으면 어인은 못 살아.",
	BURNT = "안돼애애!",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.BREWERY = {
	GENERIC = "뭐 하는 장치인지 잘 모르게써.",
	BURNT = "물 소게 있었으면 그럴 일도 업섰을거야.뻐끔",
	FERMENTING_LONG = "관찰도 워트의 일이야.",
	FERMENTING_SHORT = "거의 다 되가는것 가타.",
	DONE = "이상한 음료가 나온거 가타!",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.CAMPKETTLE_ITEM = "매끈이들이 물을 끓여마시래써."
STRINGS.CHARACTERS.WURT.DESCRIBE.CAMPKETTLE = {
	GENERIC = "텅 비었어.",
	BOILING_LONG = "미지근해.",
	BOILING_SHORY = "보글보글 꼬로로록",
	DONE = "식혀서 마시자.",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.KETTLE = {
	GENERIC = "텅 비었어",
	BURNT = "이런...",
	BOILING_LONG = "관찰도 워트의 일이야.",
	BOILING_SHORT = "좋은 향이 나는것 가타.",
	DONE = "맛있는거 마실 시간이야!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "워트가 재료를 가져올수 있어.",
	EMPTY = "엥? 아무것도 없어!",
	BOILING_LONG = "관찰도 워트의 일이야.",
	BOILING_SHORT = "좋은 향이 나는것 가타.",
	DONE = "맛있는거 마실 시간이야!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WX78

STRINGS.CHARACTERS.WX78.DESCRIBE.WELL_DRILLING = "좋다 친구여! 대지를 네 뜻대로 뚫고 나아가라"
STRINGS.CHARACTERS.WX78.DESCRIBE.WELL_DRILLING_ITEM = "안녕하신가 위대한 나의 벗이여."

STRINGS.CHARACTERS.WX78.DESCRIBE.HOLE = "날개 없는 유기체는 빠져나오지 못할것"

STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_EMPTY = "원시적인 액체 저장장치"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_CLEAN = "H2O가 담겨져 있다."
STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_DIRTY = "바이러스 농도가 짙은 스프"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_SALTY = "위험. 염소이온의 농도가 지나치게 높음"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_ICE = "포텐셜이 지나치게 낮아 형태가 고정되었다."

STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_TREE = "에너지 함량이 비교적 높은 잎 포함"
STRINGS.CHARACTERS.WX78.DESCRIBE.DUG_TEA_TREE = "땅에 있을때 더 유용할것"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_SEED = "어떻게 이 안에 나무가 들어있는가?"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_SEED_COOKED = "나무를 죽여 영양분으로 전환"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_SEED_SAPLING = "나무가 곧 생장"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEALEAVES = "비교적 높은 에너지를 가진 이파리들"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEALEAVES_DRIED = "수분을 줄인 이파리들."

STRINGS.CHARACTERS.WX78.DESCRIBE.DUG_CAFFEINBERRY = "땅에 있을때 더 유용할것"
STRINGS.CHARACTERS.WX78.DESCRIBE.CAFFEINBERRY = "토착 식물에 기생중인 외우주 생명체 감지됨"
STRINGS.CHARACTERS.WX78.DESCRIBE.CAFFEINBERRY_BEAN = "외우주 생명체의 열매"
STRINGS.CHARACTERS.WX78.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "외계물질은 소독이다."

STRINGS.CHARACTERS.WX78.DESCRIBE.CUP = "초소형 액체 저장장치."
STRINGS.CHARACTERS.WX78.DESCRIBE.CLEANWATER = "H2O가 담겨져 있다."
STRINGS.CHARACTERS.WX78.DESCRIBE.DIRTY = "바이러스 농도가 짙은 스프."
STRINGS.CHARACTERS.WX78.DESCRIBE.SALTY = "위험. 염소이온의 농도가 지나치게 높음"
STRINGS.CHARACTERS.WX78.DESCRIBE.GARBAGE = "분석 불가능한 혼돈"
STRINGS.CHARACTERS.WX78.DESCRIBE.FRUIT = "고당도 식물성 스프"
STRINGS.CHARACTERS.WX78.DESCRIBE.BERRIES_TEA = "향기로운 유사혈액"
STRINGS.CHARACTERS.WX78.DESCRIBE.POMEGRANATE_TEA = "먹는 수고를 줄였다."
STRINGS.CHARACTERS.WX78.DESCRIBE.BANANA_TEA = "미량의 방사성 물질 포함"
STRINGS.CHARACTERS.WX78.DESCRIBE.FIG_TEA = "이 안에 들은건 꽃이다,하수인들아"
STRINGS.CHARACTERS.WX78.DESCRIBE.DRAGONFRUIT_TEA = "에너지 높은 추출물."
STRINGS.CHARACTERS.WX78.DESCRIBE.GLOWBERRY = "발광성 액체전지."
STRINGS.CHARACTERS.WX78.DESCRIBE.CAFFEINBERRY_JUICE = "뜨거운 외우주 생명체의 추출물"
STRINGS.CHARACTERS.WX78.DESCRIBE.VEGGIE = "저 에너지 식물성 수프"
STRINGS.CHARACTERS.WX78.DESCRIBE.CARROT_TEA = "섭취 용이한 베타카로틴 수프."
STRINGS.CHARACTERS.WX78.DESCRIBE.CACTUS_TEA = "물이 부족하다고 해서 물속에 넣었다."
STRINGS.CHARACTERS.WX78.DESCRIBE.MULLED = "아픈 하수인들의 고 에너지 연료의 일종"
STRINGS.CHARACTERS.WX78.DESCRIBE.GREENTEA = "뜨거운 이파리 우린 물"
STRINGS.CHARACTERS.WX78.DESCRIBE.BLACKTEA = "뜨거운 말린 이파리 우린 물"
STRINGS.CHARACTERS.WX78.DESCRIBE.BLACKTEA_ICED = "차가운 이파리 우린 물이다."
STRINGS.CHARACTERS.WX78.DESCRIBE.FUER = "동굴 이파리를 우린 물."
STRINGS.CHARACTERS.WX78.DESCRIBE.MIXFLOWER = "아름다운 삶은 유기체들의 죽음."
STRINGS.CHARACTERS.WX78.DESCRIBE.HIBISCUS = "아름다운 삶은 유기체의 죽음."
STRINGS.CHARACTERS.WX78.DESCRIBE.CACTUSFLOWER = "물이 부족하다고 해서 물속에 넣었다."
STRINGS.CHARACTERS.WX78.DESCRIBE.LOTUSFLOWER = "이 식물은 고향으로 돌아갔다."
STRINGS.CHARACTERS.WX78.DESCRIBE.SUSHIBISCUS = "오류: 해석 불가능."
STRINGS.CHARACTERS.WX78.DESCRIBE.SPOILED_DRINK = "불쾌한 유기물 스프."
STRINGS.CHARACTERS.WX78.DESCRIBE.SODA = "탄소중립을 지켜라 하수인들."
STRINGS.CHARACTERS.WX78.DESCRIBE.FRUITSODA = "불건강한 하수인들의 탄산연료"
STRINGS.CHARACTERS.WX78.DESCRIBE.LLSODA = "당도 만이 자랑인 탄산연료"
STRINGS.CHARACTERS.WX78.DESCRIBE.COLA = "검은 마약성 H2CO3"
STRINGS.CHARACTERS.WX78.DESCRIBE.COLAQUANTUM = "경고: 방사성 물질 검출됨"
STRINGS.CHARACTERS.WX78.DESCRIBE.BEER = "불순물 가득한 고열량 에틸 알코올"
STRINGS.CHARACTERS.WX78.DESCRIBE.MEAD = "더이상 그들이 활용할수 없게 가공됨"
STRINGS.CHARACTERS.WX78.DESCRIBE.WINE = "휘발성 유사 혈액."
STRINGS.CHARACTERS.WX78.DESCRIBE.NOBLEWINE = "하수인들을 미치게 하는 고당도 에틸알코올."
STRINGS.CHARACTERS.WX78.DESCRIBE.SPARKLINGWINE = "CO2와 C6H12O6을 첨가한 에틸알코올이다."
STRINGS.CHARACTERS.WX78.DESCRIBE.GLOWBERRYWINE = "발광하는 마약성 에틸 알코올"
STRINGS.CHARACTERS.WX78.DESCRIBE.KUMIS = "장기보존 처리한 유기체의 젖"

STRINGS.CHARACTERS.WX78.DESCRIBE.WELL = "원시적인 수분 공급장치."
STRINGS.CHARACTERS.WX78.ACTIONFAIL.GIVE.WELL_NOTEMPTY = "적절한 에드온이 필요"
STRINGS.CHARACTERS.WX78.ACTIONFAIL.GIVE.WELL_BUSY = "작은 친구가 일을 마칠떄까지 기다려라."

STRINGS.CHARACTERS.WX78.WELLSTATUS = {
	NOTEMPTY = "적절한 에드온이 필요",
	BUSY = "작은 친구가 일을 마칠떄까지 기다려라.",
	WRONG_TIME = "이것은 규격에 맞지 않음",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.DESALINATOR = {
	EMPTY = "원시적인 염소이온 분리장치",
	PURIFY = "염소이온을 분리중",
	HASWATER = "분리, 완료",
	BURNT = "잘가라,친구여",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.BARREL = {
	GENERIC = "대용량 액체 저장장치",
	BURNT = "저장소 용량 0으로 축소됨",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.BREWERY = {
	GENERIC = "원시적인 에틸 알코올 변환장치",
	BURNT = "애처로움",
	FERMENTING_LONG = "시간이 필요",
	FERMENTING_SHORT = "거의 완료됨",
	DONE = "발효 프로세스 종료",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.CAMPKETTLE_ITEM = "소량 액체 가열용 애드온"
STRINGS.CHARACTERS.WX78.DESCRIBE.CAMPKETTLE = {
	GENERIC = "가열을 통해 미생물 소독",
	BOILING_LONG = "시간이 필요",
	BOILING_SHORY = "거의 완료됨",
	DONE = "소독 프로세스 종료",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.KETTLE = {
	GENERIC = "혐오스러운 물을 이겨내는 강력함에 경의를 표한다",
	BURNT = "좋은 기계 동지였다",
	BOILING_LONG = "시간이 필요",
	BOILING_SHORT = "거의 완료됨",
	DONE = "추출 프로세스 종료",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "너는 하수인에게 이용당하고 있다",
	EMPTY = "수용성 물질 추출 장치",
	BOILING_LONG = "시간이 필요",
	BOILING_SHORT = "거의 완료됨",
	DONE = "추출 프로세스 종료",
	PURIFY = "TODO",
	HASWATER = "TODO",
}