_G=GLOBAL
local STRINGS = _G.STRINGS
local rec = STRINGS.RECIPE_DESC
local nm = STRINGS.NAMES
local gen = STRINGS.CHARACTERS.GENERIC.DESCRIBE

--[[TUNING.BEER_ONDRINK = "Oh... I feel drunk"
TUNING.BEER_OFFDRINK = "So refreshing! I feel amazing"
TUNING.POHMEL = "That's disgusting, but I feel better now."
TUNING.STAR_BAKS = "Not Starbaks, but it's okay"
TUNING.TEA_YAWN = ""
TUNING.RED_TEA_SPEEP = ""
TUNING.barrel_ENERGY = "Energy - "
TUNING.barrel_WATERLEVEL = "%. Water Level "]]--
--[[STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_BAG = "Bag of herbs"
STRINGS.RECIPE_DESC.GRASS_BAG = "A magical bag with plants inside."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_BAG = "I should open it."]]--


-- well drilling
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_DRILLING = "It's digging a hole."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_DRILLING_ITEM = "I should keep drilling on my buisiness."
STRINGS.CHARACTERS.WILSON.DESCRIBE.WELL_DRILLING = "It's digging a hole."
--[[STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING_ITEM = "TODO"
STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING_ITEM = "TODO"
STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING_ITEM = "TODO"
STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING_ITEM = "TODO"
STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS..DESCRIBE.WELL_DRILLING_ITEM = "TODO"]]

-- wells & hole
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOLE = "I cannot see the bottom."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_ITEM = "Let's install this in the hole."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL = "It's easier to get clean water."

-- desalinator
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DESALINATOR = "Now I can get fresh water out of sea!"

-- barrel
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BARREL = "I can contain my water here."

-- brewery
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BREWERY = "It is one of the ways to store water for a long time."

-- buckets
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET = "I can fill it with water, or something else."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_FULL = "It's filled with water."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_DIRTY = "It's filled with water, but is dirty"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_SALT = "It's filled with water, but is salty"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_ICE = "Now it's useful, but I think I can take it out."

-- campkettle
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAMPKETTLE = "It always need fuel."

-- kettle
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KETTLE = "Finally, I can make tea now!"

-- portablekettle
STRINGS.CHARACTERS.GENERIC.DESCRIBE.portablekettle_ITEM = "I can take it inside my backpack!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.portablekettle = "I can take it inside my backpack!"

-- tea_trees
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_TREE = "It's a tree of tea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_TEA_TREE = "The leaves smell amazing."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED = "It's a seed of tree tea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED_COOKED = "I regret doing this."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED_SAPLING = "It will grow into a tea tree in the future."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEALEAVES = "That smell is amazing!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEALEAVES_DRIED = "The tea scent seems to have become stronger."

-- caffeinberry
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_CAFFEINBERRY = "This is a plant I could learn to love."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY = "This belongs in the ground!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_BEAN = "They could use some roasting."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "Heat definitely improved them."

-- empty_cup
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP = "For drinking tea!"

-- preparedrink

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_WATER = "I can drink it"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_WATER = "I can drink it"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_DIRTY = "I have to take risks to drink it."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_SALT = "It's not good to drink this."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_SALT = "It's not good to drink this."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_GARBAGE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_GARBAGE = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_FRUIT = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_FRUIT = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_BERRY = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_BERRY = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_POMEGRANATE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_POMEGRANATE = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_BANANA = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_BANANA = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_FIG = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_FIG = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_DRAGONFRUIT = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_DRAGONFRUIT = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_GLOWBERRY = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_GLOWBERRY = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_COFFEE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_COFFEE = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_VEGGIE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_VEGGIE = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_CARROT = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_CARROT = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_CACTUS = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_CACTUS = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_MULLED = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_MULLED = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_GREENTEA = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_GREENTEA = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_BLACKTEA = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_BLACKTEA = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_BLACKTEA_ICED = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_BLACKTEA_ICED = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_FUER = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_FUER = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_MIXFLOWER = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_MIXFLOWER = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_HIBISCUS = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_HIBISCUS = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_CACTUSFLOWER = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_CACTUSFLOWER = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_LOTUSFLOWER = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_LOTUSFLOWER = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_SUSHIBISCUS = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_SUSHIBISCUS = "TODO"

-- prepareagedrink

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_STRANG = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_STRANG = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_SODA = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_SODA = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_FRUITSODA = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_FRUITSODA = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_LLSODA = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_LLSODA = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_COLA = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_COLA = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_COLAQUANTUM = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_COLAQUANTUM = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_BEER = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_BEER = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_PULQUE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_PULQUE = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_MEAD = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_MEAD = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_FRUITWINE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_FRUITWINE = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_WINE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_WINE = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_GLOWBERRYWINE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_GLOWBERRYWINE = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_GINSENG_LIQUOR = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOTTLE_GINSENG_LIQUOR = "TODO"