_G=GLOBAL
local STRINGS = _G.STRINGS

-- SPICE_CAFFEINPEPPER SPEECH

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"

--[[STRINGS.CHARACTERS.WALTER.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.SPICE_CAFFEINPEPPER = "TODO"]]

-- PURIFICATION_TABLETS SPEECH

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PURIFICATION_TABLETS = "TODO"

--[[STRINGS.CHARACTERS.WALTER.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.PURIFICATION_TABLETS = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.PURIFICATION_TABLETS = "TODO"]]

-- DRUNK SPEECH

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DRUNK = "Oh... I feel drunk."

--[[STRINGS.CHARACTERS.WALTER.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WANDA.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WARLY.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WENDY.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WINONA.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WURT.ANNOUNCE_DRUNK = "Oh... I feel drunk."
STRINGS.CHARACTERS.WX78.ANNOUNCE_DRUNK = "Oh... I feel drunk."]]

-- DRUNK IMMUNITY SPEECH

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DRUNK_IMMUNITY = "This can't make me drunk!"

--STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_DRUNK_IMMUNITY = "This can't make me drunk!"

-- END DRUNK SPEECH

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"

--[[STRINGS.CHARACTERS.WALTER.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WANDA.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WARLY.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WENDY.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WINONA.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WURT.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"
STRINGS.CHARACTERS.WX78.ANNOUNCE_DRUNK_END = "I'm not drunk anymore. Good"]]

-- END DRUNK BY SLEEP SPEECH

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_SLEEP_END = "I feel much better"

--[[STRINGS.CHARACTERS.WALTER.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WANDA.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WARLY.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WAXWELL.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WEBBER.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WENDY.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WILLOW.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WINONA.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WOODIE.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WORMWOOD.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WORTOX.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WURT.ANNOUNCE_SLEEP_END = "I feel much better"
STRINGS.CHARACTERS.WX78.ANNOUNCE_SLEEP_END = "I feel much better"]]

-- not ready to mliking

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_NOTCHARGE = "TODO"
--[[STRINGS.CHARACTERS.WALTER.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_NOTCHARGE = "TODO."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.ANNOUNCE_NOTCHARGE = "TODO"]]

STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
--[[
STRINGS.CHARACTERS.WALTER.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WANDA.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WARLY.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WATHGRITHR.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WEBBER.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WENDY.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WINONA.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WOLFGANG.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WOODIE.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WORMWOOD.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WORTOX.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WURT.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
STRINGS.CHARACTERS.WX78.ACTIONFAIL.GIVE.NOTCAMPKETTLE = "test augment"
]]

-- GENERIC

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_DRILLING = "It's digging a hole."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_DRILLING_ITEM = "I should keep drilling on my buisiness."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOLE = "I cannot see the bottom."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET = "I can fill it with water, or something else."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_CLEAN = "It's filled with water."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_DIRTY = "It's filled with water, but is dirty."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_SALTY = "It's filled with water, but is salty."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_ICE = "Now it's useless, but I think I can take it out."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_TREE = "It's a tree of tea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_TEA_TREE = "The leaves smell amazing."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED = "It's a seed of tree tea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED_COOKED = "I regret doing this."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED_SAPLING = "It will grow into a tea tree in the future."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEALEAVES = "That smell is amazing!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEALEAVES_DRIED = "The tea scent seems to have become stronger."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_CAFFEINBERRY = "This is a plant I could learn to love."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY = "This belongs in the ground!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_BEAN = "They could use some roasting."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "Heat definitely improved them."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP = "For drinking tea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL = "It's easier to get clean water."
STRINGS.CHARACTERS.GENERIC.WELLSTATUS = {
	NOTEMPTY = "I need to take out the bucket first.",
	BUSY = "I'm getting water right now.",
	WRONG_TIME = "Can't get water with this.",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DESALINATOR = {
	EMPTY = "Now I can get fresh water out of sea!",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "Fire has beaten water. Strange.",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BARREL = {
	GENERIC = "I can contain my water here.",
	BURNT = "Fire has beaten water. Strange.",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BREWERY = {
	EMPTY = "It's one of the ways to store water for a long time.",
	BURNT = "Fire has beaten water. Strange.",
	FERMENTING_LONG = "This is going to take a while.",
	FERMENTING_SHORT = "It's almost done!",
	DONE = "Mmmmm! It's ready to drink! Then I'll bring a cup.",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "This is going to take a while.",
	BOILING_SHORT = "It's almost done!",
	DONE = "Finally! I got clean water",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KETTLE = {
	EMPTY = "It makes me thirsty. just to look at it.",
	BURNT = "Fire has beaten water. Strange.",
	BOILING_LONG = "This is going to take a while.",
	BOILING_SHORT = "It's almost done!",
	DONE = "Mmmmm! It's ready to drink! Then I'll bring a cup.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "I can take it inside my backpack!",
	EMPTY = "I bet there's nothing in there.",
	BOILING_LONG = "만드는 데에 시간이 좀 걸리겠어.",
	BOILING_SHORT = "It'll be ready in no-time!",
	DONE = "다 됐다!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}


--[[
-- WALTER -- 호기심 많은 보이스카우트 소년

STRINGS.CHARACTERS.WALTER.DESCRIBE.WELL_DRILLING = "TODO"--
STRINGS.CHARACTERS.WALTER.DESCRIBE.WELL_DRILLING_ITEM = "TODO"--

STRINGS.CHARACTERS.WALTER.DESCRIBE.HOLE = "TODO"--

STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WALTER.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WALTER.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WALTER.DESCRIBE.CUP = "For drinking tea!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WALTER.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WALTER.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WALTER.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WALTER.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WALTER.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WALTER.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WALTER.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WALTER.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WALTER.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WALTER.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WALTER.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WALTER.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WALTER.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WALTER.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WALTER.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WALTER.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WALTER.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WALTER.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WALTER.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WALTER.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WALTER.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WALTER.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WALTER.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WALTER.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WALTER.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WALTER.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "불을 끌 수 있을정도의 물이 없었나봐",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "불을 끌 수 있을정도의 물이 없었나봐",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.BREWERY = {
	GENERIC = "안에 음료가 있었으면 정말 좋겠어.",
	BURNT = "불을 끌 수 있을정도의 물이 없었나봐",
	FERMENTING_LONG = "This might take a while. Wanna see this cool bug I found in the meantime?",
	FERMENTING_SHORT = "음료 마실 시간이 거의 다 됐어!",
	DONE = "Come and get it!",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPKETTLE = {
	GENERIC = "안에 음료가 있었으면 정말 좋겠어.",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.KETTLE = {
	GENERIC = "안에 음료가 있었으면 정말 좋겠어.",
	BURNT = "불을 끌 수 있을정도의 물이 없었나봐",
	BOILING_LONG = "This might take a while. Wanna see this cool bug I found in the meantime?",
	BOILING_SHORT = "음료 마실 시간이 거의 다 됐어!",
	DONE = "Come and get it!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "그래도 모닥불 주전자보다는 못해.",
	EMPTY = "음료를 준비하려면 재료를 좀 채집해야 할 거야.",
	BOILING_LONG = "Maybe I'll organize my bug collection while I'm waiting.",
	BOILING_SHORT = "It's almost done!",
	DONE = "으음, 음료를 마실시간이다!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WANDA

STRINGS.CHARACTERS.WANDA.DESCRIBE.WELL_DRILLING = "빨리빨리 뚤으라고!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.WELL_DRILLING_ITEM = "일단 이것부터 작동시켜야겠어."

STRINGS.CHARACTERS.WANDA.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WANDA.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WANDA.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WANDA.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WANDA.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WANDA.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WANDA.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WANDA.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WANDA.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WANDA.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WANDA.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WANDA.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WANDA.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WANDA.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WANDA.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WANDA.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WANDA.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WANDA.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WANDA.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WANDA.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WANDA.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WANDA.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WANDA.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WANDA.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WANDA.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WANDA.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WANDA.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WANDA.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WANDA.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WANDA.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WANDA.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WANDA.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "Well that's a setback.",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "Well that's a setback.",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.BREWERY = {
	GENERIC = "차라리 그냥... 배리나 당근을 채칩해서 먹든지 해야겠다.",
	BURNT = "Well that's a setback.",
	FERMENTING_LONG = "내가 이래서 이 짓를 싫어해. 끝날 기미가 안보이잖아!",
	FERMENTING_SHORT = "It has to be almost done by now, right?",
	DONE = "마침내 음료가 다 됐군!",
}

STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WALTER.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.KETTLE = {
	GENERIC = "차라리 그냥... 배리나 당근을 채칩해서 먹든지 해야겠다.",
	BURNT = "Well that's a setback.",
	BOILING_LONG = "내가 이래서 이 짓를 싫어해. 끝날 기미가 안보이잖아!",
	BOILING_SHORT = "It has to be almost done by now, right?",
	DONE = "마침내 음료가 다 됐군!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WANDA.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "난 고급 음료니 뭐니 귀찮아서 싫어.",
	EMPTY = "우리는 냄새는 전혀 안 나는데.",
	BOILING_LONG = "Ohhh I wish it would just hurry up!",
	BOILING_SHORT = "Surely it won't take too much longer?",
	DONE = "마침내 음료가 다 됐군!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WARLY

STRINGS.CHARACTERS.WARLY.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WARLY.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WARLY.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WARLY.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WARLY.DESCRIBE.CUP = "For drinking tea!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WARLY.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WARLY.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WARLY.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WARLY.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WARLY.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WARLY.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WARLY.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WARLY.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WARLY.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WARLY.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WARLY.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WARLY.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WARLY.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WARLY.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WARLY.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WARLY.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WARLY.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WARLY.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WARLY.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WARLY.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WARLY.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WARLY.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WARLY.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WARLY.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WARLY.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WARLY.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WARLY.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}


STRINGS.CHARACTERS.WARLY.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT ="Tragique.",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "Tragique.",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.BREWERY = {
	GENERIC = "양조기도 비고, 내 맘도 비었네.",
	BURNT = "Tragique.",
	FERMENTING_LONG = "A masterpiece takes time.",
	FERMENTING_SHORT = "Nearly there...",
	DONE = "Ahh, fini!",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WARLY.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.KETTLE = {
	GENERIC = "주전자도 비고, 내 맘도 비었네.",
	BURNT = "Tragique.",
	BOILING_LONG = "A masterpiece takes time.",
	BOILING_SHORT = "Nearly there...",
	DONE = "Ahh, fini!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WARLY.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "What new culinary adventures shall we undertake, old friend?",
	EMPTY = "I would never leave home without it!",
	BOILING_LONG = "The flavors need time to meld.",
	BOILING_SHORT = "빨리 음료를 내가야 한다고!",
	DONE = "Pickup! Oh, old habits...",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WATHGRITHR

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "The fire reigned supreme.",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "The fire reigned supreme.",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.BREWERY = {
	GENERIC = "Nothing in there.",
	BURNT = "The fire reigned supreme.",
	FERMENTING_LONG = "Might as well do something whilst I wait.",
	FERMENTING_SHORT = "Shouldn't be long now!",
	DONE = "What have we here?",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.KETTLE = {
	EMPTY = "Nothing in there.",
	BURNT = "The fire reigned supreme.",
	BOILING_LONG = "Might as well do something whilst I wait.",
	BOILING_SHORT = "Shouldn't be long now!",
	DONE = "What have we here?",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "생명수를 만드는 주전자로군.",
	EMPTY = "물 한 방울도 없군...",
	BOILING_LONG = "The thirst parches mine throat... make haste, kettle!",
	BOILING_SHORT = "This will be done swiftly!",
	DONE = "먹을 음료가 있나?",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WAXWELL

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WAXWELL.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "마르다 못해 타버렸군.",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "마르다 못해 타버렸군.",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.BREWERY = {
	GENERIC = "생각만 해도 속이 시원해지는군",
	BURNT = "마르다 못해 타버렸군.",
	FERMENTING_LONG = "Wait for it..",
	FERMENTING_SHORT = "Here it comes!",
	DONE = "Finally, some quality drink",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KETTLE = {
	GENERIC = "생각만 해도 속이 따뜻해지는군",
	BURNT = "마르다 못해 타버렸군.",
	BOILING_LONG = "Wait for it..",
	BOILING_SHORT = "Here it comes!",
	DONE = "Finally, some quality drink",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "격식 있는 음료 도구야.",
	EMPTY = "쓸쓸하게도 음료가 하나도 없어.",
	BOILING_LONG = "I must exercise patience...",
	BOILING_SHORT = "It will be finished shortly.",
	DONE = "마실만한 게 나온 건지나 빌어야지.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WEBBER

STRINGS.CHARACTERS.WEBBER.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WAXWELLWEBBER.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WEBBER.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}


STRINGS.CHARACTERS.WEBBER.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "Someone must have left the fire going.",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "Someone must have left the fire going.",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.BREWERY = {
	GENERIC = "재료를 넣으면 다른 음료가 나와.",
	BURNT = "Someone must have left the fire going.",
	FERMENTING_LONG = "It won't be done for a while.",
	FERMENTING_SHORT = "Almost ready!",
	DONE = "물을 마실 시간이야",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.KETTLE = {
	GENERIC = "재료를 넣으면 다른 음료가 나와.",
	BURNT = "Someone must have left the fire going.",
	BOILING_LONG = "It won't be done for a while.",
	BOILING_SHORT = "Almost ready!",
	DONE = "물을 마실 시간이야",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WEBBER.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "Makes yummies!",
	EMPTY = "Aw, there's nothing in there.",
	BOILING_LONG = "This is taking so loooong!",
	BOILING_SHORT = "곧 있으면 음료가 준비될 거야!",
	DONE = "으으음! 어서 마시자!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WENDY

STRINGS.CHARACTERS.WENDY.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WENDY.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WENDY.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WENDY.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WENDY.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WENDY.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WENDY.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WENDY.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WENDY.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WENDY.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WENDY.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WENDY.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WENDY.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WENDY.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WENDY.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WENDY.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WENDY.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WENDY.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WENDY.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WENDY.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WENDY.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WENDY.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WENDY.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WENDY.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "Burnt to a crisp.",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "Burnt to a crisp.",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.BREWERY = {
	GENERIC = "As empty as my soul.",
	BURNT = "Burnt to a crisp.",
	FERMENTING_LONG = "Whatever's in there isn't dead yet.",
	FERMENTING_SHORT = "좀 더 발효 해야 해.",
	DONE = "Finally, drink",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.KETTLE = {
	GENERIC = "As empty as my soul.",
	BURNT = "Burnt to a crisp.",
	BOILING_LONG = "Whatever's in there isn't dead yet.",
	BOILING_SHORT = "It needs to boil.",
	DONE = "Finally, drink",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WENDY.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "목마름이 내 작은 목를 물어뜯을 때를 위해...",
	EMPTY = "A drinkless void.",
	BOILING_LONG = "어쩌면 다 되기도 전에 탈수로 죽을지도.",
	BOILING_SHORT = "It will all be over soon.",
	DONE = "Another menial task has been completed.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WICKERBOTTOM

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}


STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "Now it's truly derelict.",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "Now it's truly derelict.",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BREWERY = {
	GENERIC = "이건 음료를 안 만들고 있는 때는 황량해 보여.",
	BURNT = "Now it's truly derelict.",
	FERMENTING_LONG = "It's got a bit to go before it's ready.",
	FERMENTING_SHORT = "Almost done!",
	DONE = "Drink time!",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KETTLE = {
	EMPTY = "이건 음료를 안 만들고 있는 때는 황량해 보여.",
	BURNT = "Now it's truly derelict.",
	BOILING_LONG = "It's got a bit to go before it's ready.",
	BOILING_SHORT = "Almost done!",
	DONE = "Tea time!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "어디서든 들고 다닐수 있겠구나.",
	EMPTY = "Hm, perhaps I'll whip something up.",
	BOILING_LONG = "Patience is a virtue!",
	BOILING_SHORT = "This will be finished in no time at all.",
	DONE = "Smells nourishing.",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WILLOW

STRINGS.CHARACTERS.WILLOW.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WILLOW.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "At least it went out in a blaze of glory.",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "At least it went out in a blaze of glory.",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.BREWERY = {
	GENERIC = "이거에는 불을 안 쓰는거는 참 슬퍼",
	BURNT = "At least it went out in a blaze of glory.",
	FERMENTING_LONG = "불을 쓰면 더 빠르게 발효되지 않을까?",
	FERMENTING_SHORT = "슬프게도 불 없이도 완성이 거의 다 됬네.",
	DONE = "불 없이 만든음료는 좀 미덥단 말이지",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.KETTLE = {
	EMPTY = "모든 음료은 불로 살균해야 해.",
	BURNT = "At least it went out in a blaze of glory.",
	BOILING_LONG = "The fire still has quite a bit of work to do.",
	BOILING_SHORT = "The fire is doing its thing!",
	DONE = "Fire makes everything better. Mmm!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WILLOW.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "이 멍청한걸 들고 다녀야해?",
	EMPTY = "멍청한 속 빈 주전자 같은이.",
	BOILING_LONG = "Ughhh, this is taking forever!",
	BOILING_SHORT = "Come on fire, do your thing!",
	DONE = "좋았어. 이제 마시자!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WINONA

STRINGS.CHARACTERS.WINONA.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WINONA.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WINONA.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WINONA.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WINONA.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WINONA.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WINONA.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WINONA.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WINONA.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WINONA.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WINONA.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WINONA.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WINONA.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WINONA.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WINONA.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WINONA.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WINONA.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WINONA.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WINONA.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WINONA.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WINONA.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WINONA.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WINONA.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WINONA.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WINONA.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WINONA.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WINONA.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WINONA.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WINONA.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WINONA.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "You guys like gristle, right?",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "You guys like gristle, right?",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.BREWERY = {
	GENERIC = "TODO.",
	BURNT = "You guys like gristle, right?",
	FERMENTING_LONG = "Still got a bit of a wait.",
	FERMENTING_SHORT = "Almost!",
	DONE = "음료를 마십시다!",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WINONA.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.KETTLE = {
	EMPTY = "내가 커피를 잘 타는데 말이야.",
	BURNT = "You guys like gristle, right?",
	BOILING_LONG = "Still got a bit of a wait.",
	BOILING_SHORT = "Almost!",
	DONE = "음료를 마십시다!",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WINONA.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "이 고급진 주전자를 어디든지 들고 다닐수 있지.",
	EMPTY = "Could use some ingredients in there.",
	BOILING_LONG = "All good things take time.",
	BOILING_SHORT = "This'll be done lickety-split!",
	DONE = "Let's see if all that fuss was worth it",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WOLFGANG

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WOLFGANG.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.BREWERY = {
	GENERIC = "TODO",
	BURNT = "TODO",
	FERMENTING_LONG = "TODO",
	FERMENTING_SHORT = "TODO",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.KETTLE = {
	EMPTY = "TODO",
	BURNT = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "TODO",
	EMPTY = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WOODIE

STRINGS.CHARACTERS.WOODIE.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WOODIE.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.BREWERY = {
	GENERIC = "TODO",
	BURNT = "TODO",
	FERMENTING_LONG = "TODO",
	FERMENTING_SHORT = "TODO",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.KETTLE = {
	EMPTY = "TODO",
	BURNT = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WOODIE.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "TODO",
	EMPTY = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WORMWOOD

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WORMWOOD.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.BREWERY = {
	GENERIC = "TODO",
	BURNT = "TODO",
	FERMENTING_LONG = "TODO",
	FERMENTING_SHORT = "TODO",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.KETTLE = {
	EMPTY = "TODO",
	BURNT = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "TODO",
	EMPTY = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WORTOX

STRINGS.CHARACTERS.WORTOX.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WORTOX.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WORTOX.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.BREWERY = {
	GENERIC = "TODO",
	BURNT = "TODO",
	FERMENTING_LONG = "TODO",
	FERMENTING_SHORT = "TODO",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.KETTLE = {
	EMPTY = "TODO",
	BURNT = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WORTOX.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "TODO",
	EMPTY = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WURT

STRINGS.CHARACTERS.WURT.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WURT.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WURT.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WURT.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WURT.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WURT.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WURT.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WURT.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WURT.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WURT.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WURT.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WURT.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WURT.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WURT.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WURT.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WURT.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WURT.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WURT.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WURT.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WURT.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WURT.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WURT.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WURT.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WURT.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WURT.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WURT.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WURT.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WURT.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WURT.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WURT.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WURT.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WURT.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WURT.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WURT.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WURT.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WURT.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WURT.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WURT.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WURT.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WURT.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WURT.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WURT.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.BREWERY = {
	GENERIC = "TODO",
	BURNT = "TODO",
	FERMENTING_LONG = "TODO",
	FERMENTING_SHORT = "TODO",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WURT.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.KETTLE = {
	GENERIC = "TODO",
	BURNT = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WURT.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "TODO",
	EMPTY = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

-- WX78

STRINGS.CHARACTERS.WX78.DESCRIBE.WELL_DRILLING = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.WELL_DRILLING_ITEM = "TODO"

STRINGS.CHARACTERS.WX78.DESCRIBE.HOLE = "TODO"

STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_CLEAN = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_DIRTY = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_SALTY = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.BUCKET_ICE = "TODO"

STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_TREE = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.DUG_TEA_TREE = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_SEED = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_SEED_COOKED = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEA_SEED_SAPLING = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEALEAVES = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.TEALEAVES_DRIED = "TODO"

STRINGS.CHARACTERS.WX78.DESCRIBE.DUG_CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.CAFFEINBERRY = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.CAFFEINBERRY_BEAN = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "TODO"

STRINGS.CHARACTERS.WX78.DESCRIBE.CUP = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.WATER = "I can drink it"
STRINGS.CHARACTERS.WX78.DESCRIBE.DIRTY = "I have to take risks to drink it."
STRINGS.CHARACTERS.WX78.DESCRIBE.SALTY = "It's not good to drink this."
STRINGS.CHARACTERS.WX78.DESCRIBE.GARBAGE = "I messed up the water."
STRINGS.CHARACTERS.WX78.DESCRIBE.FRUIT = "It has a strong fruity."
STRINGS.CHARACTERS.WX78.DESCRIBE.BERRIES_TEA = "That smell is tasty."
STRINGS.CHARACTERS.WX78.DESCRIBE.POMEGRANATE_TEA = "Now it's useful!"
STRINGS.CHARACTERS.WX78.DESCRIBE.BANANA_TEA = "It smells exotic."
STRINGS.CHARACTERS.WX78.DESCRIBE.FIG_TEA = "It smells stronger than Barry tea."
STRINGS.CHARACTERS.WX78.DESCRIBE.DRAGONFRUIT_TEA = "Smells really good!"
STRINGS.CHARACTERS.WX78.DESCRIBE.GLOWBERRY = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WX78.DESCRIBE.DD_COFFEE = "Smells delicious and energizing!"
STRINGS.CHARACTERS.WX78.DESCRIBE.VEGGIE = "Uh, the smell like vegetably."
STRINGS.CHARACTERS.WX78.DESCRIBE.CARROT_TEA = "I hope it will tasty."
STRINGS.CHARACTERS.WX78.DESCRIBE.CACTUS_TEA = "It smells very exotic."
STRINGS.CHARACTERS.WX78.DESCRIBE.MULLED = "There's nothing like this when you're sick!"
STRINGS.CHARACTERS.WX78.DESCRIBE.GREENTEA = "Smells like real tea!"
STRINGS.CHARACTERS.WX78.DESCRIBE.BLACKTEA = "I need milk."
STRINGS.CHARACTERS.WX78.DESCRIBE.BLACKTEA_ICED = "It's very cool."
STRINGS.CHARACTERS.WX78.DESCRIBE.FUER = "It's not black tea or green tea, weird."
STRINGS.CHARACTERS.WX78.DESCRIBE.MIXFLOWER = "It smells very strong."
STRINGS.CHARACTERS.WX78.DESCRIBE.HIBISCUS = "Sweet Indian tea."
STRINGS.CHARACTERS.WX78.DESCRIBE.CACTUSFLOWER = "Amazing exotic tea."
STRINGS.CHARACTERS.WX78.DESCRIBE.LOTUSFLOWER = "It smells a little muddy."
STRINGS.CHARACTERS.WX78.DESCRIBE.SUSHIBISCUS = "This cannot be explained scientifically."
STRINGS.CHARACTERS.WX78.DESCRIBE.SPOILED = "It did't ferment and rotted."
STRINGS.CHARACTERS.WX78.DESCRIBE.SODA = "It tastes pungent."
STRINGS.CHARACTERS.WX78.DESCRIBE.FRUITSODA = "It's a bit better!"
STRINGS.CHARACTERS.WX78.DESCRIBE.LLSODA = "I think, I made a new kind of drink."
STRINGS.CHARACTERS.WX78.DESCRIBE.COLA = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WX78.DESCRIBE.COLAQUANTUM = "It's very scientifically outstanding!"
STRINGS.CHARACTERS.WX78.DESCRIBE.BEER = "I didn't know I'd see this again."
STRINGS.CHARACTERS.WX78.DESCRIBE.MEAD = "It's light or dark?"
STRINGS.CHARACTERS.WX78.DESCRIBE.WINE = "It's a very traditional drink."
STRINGS.CHARACTERS.WX78.DESCRIBE.NOBLEWINE = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.SPARKLINGWINE = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.GLOWBERRYWINE = "It emits light even though It's brewed, weird."
STRINGS.CHARACTERS.WX78.DESCRIBE.KUMIS = "TODO"

STRINGS.CHARACTERS.WX78.DESCRIBE.WELL = "TODO"
STRINGS.CHARACTERS.WX78.WELLSTATUS = {
	NOTEMPTY = "TODO",
	BUSY = "TODO",
	WRONG_TIME = "TODO",
}


STRINGS.CHARACTERS.WX78.DESCRIBE.DESALINATOR = {
	EMPTY = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.BARREL = {
	GENERIC = "TODO",
	BURNT = "TODO",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.BREWERY = {
	GENERIC = "TODO",
	BURNT = "TODO",
	FERMENTING_LONG = "TODO",
	FERMENTING_SHORT = "TODO",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.CAMPKETTLE_ITEM = "TODO"
STRINGS.CHARACTERS.WX78.DESCRIBE.CAMPKETTLE = {
	GENERIC = "TODO",
	BOILING_LONG = "TODO.",
	BOILING_SHORY = "TODO.",
	DONE = "TODO",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.KETTLE = {
	GENERIC = "TODO",
	BURNT = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}

STRINGS.CHARACTERS.WX78.DESCRIBE.PORTABLEKETTLE_ITEM = {
	GENERIC = "TODO",
	EMPTY = "TODO",
	BOILING_LONG = "TODO",
	BOILING_SHORT = "TODO",
	DONE = "TODO",
	PURIFY = "TODO",
	HASWATER = "TODO",
}]]
