_G=GLOBAL
local STRINGS = _G.STRINGS

STRINGS.ACTIONS.BOIL = "Boil"
STRINGS.ACTIONS.DRINKING = "Drink"
STRINGS.TAKEWATER = "Take Water"
STRINGS.GITWATER = "Get Water"
STRINGS.GITDRINK = "Get Drink"
STRINGS.ACTIONS.DRAIN = "Drain"
STRINGS.ACTIONS.PURIFY = "Purify"

-- well drilling
STRINGS.NAMES.WELL_DRILLING ="Well Drill"
STRINGS.NAMES.WELL_DRILLING_ITEM = "Well Drill"
STRINGS.RECIPE_DESC.WELL_DRILLING_ITEM = "Make a hole in the ground."

-- wells & hole
STRINGS.NAMES.HOLE = "Hole"
STRINGS.NAMES.WELL = "Well"
STRINGS.NAMES.WELL_ITEM = "Well Parts"
STRINGS.RECIPE_DESC.WELL_ITEM = "All's well there's well."

-- desalinator
STRINGS.NAMES.DESALINATOR = "Desalinator"
STRINGS.RECIPE_DESC.DESALINATOR = "Yes, the water is made of water."

-- barrel
STRINGS.NAMES.BARREL = "Barrel"
STRINGS.RECIPE_DESC.BARREL = "A barrel of water is funnier than a barrel of monkeys."

-- brewery
STRINGS.NAMES.BREWERY = "Brewery"
STRINGS.RECIPE_DESC.BREWERY = "Can make delicious drinks. maybe?"

-- buckets
STRINGS.NAMES.BUCKET = "Bucket"
STRINGS.RECIPE_DESC.BUCKET = "An empty bucket"
STRINGS.NAMES.BUCKET_FULL = "Bucket with {drink}"
STRINGS.NAMES.CLEAN = "Water"
STRINGS.NAMES.DIRTY = "Dirty Water"
STRINGS.NAMES.SALTY = "Sea Water"
STRINGS.NAMES.BUCKET_ICE = "Ice Bucket"

-- campkettle
STRINGS.NAMES.CAMPKETTLE = "Camp Kettle"
STRINGS.RECIPE_DESC.CAMPKETTLE = "Your kettle for first times."

-- kettle
STRINGS.NAMES.KETTLE	= "Kettle"
STRINGS.RECIPE_DESC.KETTLE = "The last thing of your past life."

-- portablekettle
STRINGS.NAMES.PORTABLEKETTLE_ITEM	= "Portable Kettle"
STRINGS.NAMES.PORTABLEKETTLE = "Portable Kettle"
STRINGS.RECIPE_DESC.PORTABLEKETTLE_ITEM = "It's easy to carry around."

--purification_tablets
STRINGS.NAMES.PURIFICATION_TABLETS = "Purification Tablets"
STRINGS.RECIPE_DESC.PURIFICATION_TABLETS = "TODO"

-- tea_trees
STRINGS.NAMES.TEA_TREE = "Tea Tree"
STRINGS.NAMES.DUG_TEA_TREE = "Tea Tree" 
STRINGS.NAMES.TEA_SEED = "Tea Seed"
STRINGS.NAMES.TEA_SEED_COOKED = "Roast Tea Seed"
STRINGS.NAMES.TEA_SEED_SAPLING = "Tea Tree Sapling"
STRINGS.NAMES.TEALEAVES = "Tea Leaves"
STRINGS.NAMES.TEALEAVES_DRIED = "Dried Tea Leaves."

-- caffeinberry
STRINGS.NAMES.DUG_CAFFEINBERRY = "Coffee Plant" 
STRINGS.NAMES.CAFFEINBERRY = "Coffee Plant" 
STRINGS.NAMES.CAFFEINBERRY_BEAN = "Coffee Beans"
STRINGS.NAMES.CAFFEINBERRY_BEAN_COOKED = "Roast Coffee Beans"

-- empty_cup
STRINGS.NAMES.CUP = "Empty Cup"
STRINGS.RECIPE_DESC.CUP = "Container for drinks."

-- 정재알약스트링
STRINGS.NAMES.CUP_WATER = "Cup of Water"
STRINGS.NAMES.BOTTLE_WATER = "Bottle of Water"
STRINGS.NAMES.CUP_DIRTY = "Cup of Dirty Water"
STRINGS.NAMES.BOTTLE_DIRTY = "Bottle of Dirty Water"
STRINGS.RECIPE_DESC.CUP_WATER = "TODO"
STRINGS.RECIPE_DESC.BOTTLE_WATER = "TODO"

-- preparedrink

STRINGS.NAMES.CUP_ITEM = "Cup of {drink}"
STRINGS.NAMES.BOTTLE_ITEM = "Bottle of {drink}"
STRINGS.NAMES.WATER = "Water"
STRINGS.NAMES.DIRTY = "Dirty Water"
STRINGS.NAMES.SALT = "Sea Water"
STRINGS.NAMES.GARBAGE = "Wet Goop"
STRINGS.NAMES.FRUIT = "Mix Fruit Tea"
STRINGS.NAMES.BERRIES_TEA = "Berry Tea"
STRINGS.NAMES.POMEGRANATE_TEA = "Pomegranate Tea"
STRINGS.NAMES.BANANA_TEA = "Tropic Tea"
STRINGS.NAMES.FIG_TEA = "Fig Tea"
STRINGS.NAMES.DRAGONFRUIT_TEA = "DragonFruit Tea"
STRINGS.NAMES.GLOWBERRY = "Glowberry Tea"
STRINGS.NAMES.DD_COFFEE = "Coffee"
STRINGS.NAMES.VEGGIE = "Mix Veggie Tea"
STRINGS.NAMES.CARROT_TEA = "Carrot Tea"
STRINGS.NAMES.CACTUS_TEA = "Cactus Tea"
STRINGS.NAMES.MULLED = "Mulled"
STRINGS.NAMES.GREENTEA = "Green Tea"
STRINGS.NAMES.BLACKTEA = "Black Tea"
STRINGS.NAMES.BLACKTEA_ICED = "Black Tea Iced"
STRINGS.NAMES.FUER = "Fuer Tea"
STRINGS.NAMES.MIXFLOWER = "Flower Medley Tea"
STRINGS.NAMES.HIBISCUS = "Hibiscus Tea"
STRINGS.NAMES.CACTUSFLOWER = "Cactus Flower Tea"
STRINGS.NAMES.LOTUSFLOWER = "Lotus Flower Tea"
STRINGS.NAMES.SUSHIBISCUS = "Hibiscus Tea"

-- 유령차 유채이탈 관련 코드
STRINGS.NAMES.CUP_GHOSTLY_TEA = "Cup of Ghostly Tea"
STRINGS.NAMES.BOTTLE_GHOSTLY_TEA = "Bottle of Ghostly Tea"
STRINGS.NAMES.DEATH_BY_TEA = "Ghostly Tea"

-- prepareagedrink

STRINGS.NAMES.STRANG = "Rotten"
STRINGS.NAMES.SODA = "Sparkling Water"
STRINGS.NAMES.FRUITSODA = "Fruit Soda"
STRINGS.NAMES.LLSODA = "Sweet Soda"
STRINGS.NAMES.COLA = "Cola"
STRINGS.NAMES.COLAQUANTUM = "Cola Quantum"
STRINGS.NAMES.BEER = "Corn Beer"
STRINGS.NAMES.MEAD = "Mead"
STRINGS.NAMES.WINE = "Wine"
STRINGS.NAMES.NOBLEWINE = "Noble Wine"
STRINGS.NAMES.SPARKLINGWINE = "Sparkling Wine"
STRINGS.NAMES.GLOWBERRYWINE = "Glowberry Wine"
STRINGS.NAMES.KUMIS = "Kumis"