STRINGS.UI.CRAFTING_FILTERS.HYDRATION = "Hydration"

STRINGS.ACTIONS.MILK = "Mlik"
STRINGS.ACTIONS.BOIL = "끓이기"
STRINGS.ACTIONS.DRINK = "마시기"
--STRINGS.ACTIONS.TAKEWATER = "Fill"
STRINGS.ACTIONS.GIVEWATER = "물 넣기"
--STRINGS.ACTIONS.GET_DRINK = "Get Drink"
STRINGS.ACTIONS.DRAIN = "비우기"
STRINGS.ACTIONS.PURIFY = "정화하기"
STRINGS.ACTIONS.MILKINGTOOL = "Milk"

-- well drilling
STRINGS.NAMES.WELL_DRILLING ="우물 드릴"
STRINGS.NAMES.WELL_DRILLING_ITEM = "우물 드릴"
STRINGS.RECIPE_DESC.WELL_DRILLING_ITEM = "땅에다가 구멍을 만듭니다."

-- wells & hole
STRINGS.NAMES.HOLE = "구멍"
STRINGS.NAMES.WELL = "우물"
STRINGS.NAMES.WELL_ITEM = "우물 제작 키트"
STRINGS.RECIPE_DESC.WELL_ITEM = "우물이 있는것은 좋은것이다."

-- desalinator
STRINGS.NAMES.DESALINATOR = "제염기"
STRINGS.RECIPE_DESC.DESALINATOR = "좋아, 물로 물을 만드는거다."

-- barrel
STRINGS.NAMES.BARREL = "통"
STRINGS.RECIPE_DESC.BARREL = "원숭이 미 포함."

-- brewery
STRINGS.NAMES.BREWERY = "양조기"
STRINGS.RECIPE_DESC.BREWERY = "맛있는 음료를 만들 수 있다. 아마도?"

-- buckets
STRINGS.NAMES.BUCKET_EMPTY = "Bucket"
STRINGS.RECIPE_DESC.BUCKET_EMPTY = "An empty bucket."
--[[STRINGS.NAMES.BUCKET_CLEAN = "Bucket o' Water"
STRINGS.NAMES.BUCKET_DIRTY = "Bucket o' Dirty Water"
STRINGS.NAMES.BUCKET_SALTY = "Bucket o' Salty Water"
STRINGS.NAMES.BUCKET_ICE = "Ice Bucket"]]

-- campkettle
STRINGS.NAMES.CAMPKETTLE_ITEM = "Camp Kettle Kit"
STRINGS.RECIPE_DESC.CAMPKETTLE_ITEM = "Your kettle for first times."
STRINGS.NAMES.CAMPKETTLE = "Camp Kettle"

-- kettle
STRINGS.NAMES.KETTLE	= "Kettle"
STRINGS.RECIPE_DESC.KETTLE = "The last thing of your past life."

-- portablekettle
STRINGS.NAMES.PORTABLEKETTLE_ITEM	= "Portable Kettle"
STRINGS.NAMES.PORTABLEKETTLE = "Portable Kettle"
STRINGS.RECIPE_DESC.PORTABLEKETTLE_ITEM = "It's easy to carry around."

--purification_tablets
STRINGS.NAMES.PURIFICATION_TABLETS = "Purification Tablets"
STRINGS.RECIPE_DESC.PURIFICATION_TABLETS = "TODO"

-- tea_trees
STRINGS.NAMES.TEA_TREE = "Tea Tree"
STRINGS.NAMES.DUG_TEA_TREE = "Tea Tree" 
STRINGS.NAMES.TEA_SEED = "Tea Seed"
STRINGS.NAMES.TEA_SEED_COOKED = "Roast Tea Seed"
STRINGS.NAMES.TEA_SEED_SAPLING = "Tea Tree Sapling"
STRINGS.NAMES.TEALEAVES = "Tea Leaves"
STRINGS.NAMES.TEALEAVES_DRIED = "Dried Tea Leaves."

-- caffeinberry
STRINGS.NAMES.DUG_CAFFEINBERRY = "Coffee Plant" 
STRINGS.NAMES.CAFFEINBERRY = "Coffee Plant"
STRINGS.NAMES.CAFFEINBERRY_BEAN = "Coffee Beans"
STRINGS.NAMES.CAFFEINBERRY_BEAN_COOKED = "Roast Coffee Beans"
STRINGS.NAMES.SPICE_CAFFEINPEPPER = "Pepper Crumble"
STRINGS.RECIPE_DESC.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.NAMES.SPICE_CAFFEINPEPPER_FOOD = "Peppered {food}"

-- empty_cup
--[[STRINGS.NAMES.CUP = "Empty Cup"
STRINGS.RECIPE_DESC.CUP = "Container for drinks."]]

-- 정재알약스트링
--[[STRINGS.NAMES.WATER_CLEAN = "Water"
STRINGS.NAMES.WATER_DIRTY = "Dirty Water"
STRINGS.RECIPE_DESC.CUP_WATER = "TODO"
STRINGS.RECIPE_DESC.BOTTLE_WATER = "TODO"]]

-- preparedrink

--[[STRINGS.NAMES.CUP_ITEM = "Cup of {drink}"
STRINGS.NAMES.BOTTLE_ITEM = "Bottle of {drink}"]]
STRINGS.NAMES.WATER_CLEAN = "Water"
STRINGS.NAMES.WATER_DIRTY = "Dirty Water"
STRINGS.NAMES.WATER_SALTY = "Salty Water"
STRINGS.NAMES.GOOPYDRINK = "Wet Goop"
STRINGS.NAMES.FRUITJUICE = "Mix-Fruit Juice"
STRINGS.NAMES.BERRIES_TEA = "Berry Tea"
STRINGS.NAMES.POMEGRANATE_JUICE = "Pomegranate Juice"
STRINGS.NAMES.BANANA_TEA = "Tropic Tea"
STRINGS.NAMES.FIG_JUICE = "Fig Tea"
STRINGS.NAMES.DRAGONJUICE = "DragonFruit Tea"
STRINGS.NAMES.GLOWBERRYJUICE = "Glowberry Tea"
STRINGS.NAMES.CAFFEINBERRY_JUICE = "Coffee"
STRINGS.NAMES.VEGGIE_TEA = "Mix Veggie Tea"
STRINGS.NAMES.CARROT_TEA = "Carrot Tea"
STRINGS.NAMES.CACTUS_TEA = "Cactus Tea"
STRINGS.NAMES.MULLED = "Mulled Drink"
STRINGS.NAMES.GREENTEA = "Green Tea"
STRINGS.NAMES.BLACKTEA = "Black Tea"
STRINGS.NAMES.BLACKTEA_ICED = "Black Tea Iced"
STRINGS.NAMES.FUER = "Fuer Tea"
STRINGS.NAMES.MIXFLOWER = "Flower Medley Tea"
STRINGS.NAMES.HIBISCUSTEA = "Hibiscus Tea"
STRINGS.NAMES.CACTUSFLOWER_TEA = "Cactus Flower Tea"
STRINGS.NAMES.LOTUSTEA = "Lotus Flower Tea"
STRINGS.NAMES.SUSHIBISCUS = "히비스커스 차"

-- 유령차 유채이탈 관련 코드
STRINGS.NAMES.GHOSTLY_TEA = "유령 차"
--[[STRINGS.NAMES.BOTTLE_GHOSTLY_TEA = "Bottle of Ghostly Tea"
STRINGS.NAMES.DEATH_BY_TEA = "Ghostly Tea"]]

-- prepareagedrink

STRINGS.NAMES.SPOILED_DRINK = "썩은 음료"
STRINGS.NAMES.SODA = "탄산수"
STRINGS.NAMES.FRUITSODA = "과일 소다"
STRINGS.NAMES.LEMONLIMESODA = "달콤한 소다"
STRINGS.NAMES.COLA = "콜라"
STRINGS.NAMES.COLAQUANTUM = "콜라 퀀텀"
STRINGS.NAMES.BEER = "옥수수 맥주"
STRINGS.NAMES.MEAD = "Mead"
STRINGS.NAMES.WINE = "와인"
STRINGS.NAMES.NOBLEWINE = "부유 와인"
STRINGS.NAMES.SPARKLINGWINE = "스파클링 와인"
STRINGS.NAMES.GLOWBERRYWINE = "Glowberry Wine"
STRINGS.NAMES.KUMIS = "크므스"