STRINGS.UI.CRAFTING_FILTERS.HYDRATION = "Hydration"

STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SLEEP_AND_DETOX = "잠이 듦 & 해장"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_MULLED = "잠이 듦 & 강력한 해장"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CAFFINE = "이동 속력 증가"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_COLA = "최고의 음료"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_COLAQUANTUM = "소울 드링크"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_INTOXICATION = "취함 & 경감"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_INTOXICATION_GLOW = "취함 & 경감 & 빛남"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SUS = "수상함"

STRINGS.ACTIONS.MILK = "우유 얻기"
STRINGS.ACTIONS.BOIL = "끓이기"
STRINGS.ACTIONS.DRINK = "마시기"
--STRINGS.ACTIONS.TAKEWATER = "Fill"
STRINGS.ACTIONS.GIVEWATER = "물 넣기"
--STRINGS.ACTIONS.GET_DRINK = "Get Drink"
STRINGS.ACTIONS.DRAIN = "비우기"
STRINGS.ACTIONS.PURIFY = "정화하기"
STRINGS.ACTIONS.MILKINGTOOL = "우유 얻기"

-- well drilling
STRINGS.NAMES.WELL_DRILLING ="우물 드릴"
STRINGS.NAMES.WELL_DRILLING_ITEM = "우물 드릴"
STRINGS.RECIPE_DESC.WELL_DRILLING_ITEM = "땅에다가 구멍을 만듭니다."

-- wells & hole
STRINGS.NAMES.HOLE = "구멍"
STRINGS.NAMES.WELL = "우물"
STRINGS.NAMES.WELL_SPRINKLER = "스프링쿨러"

STRINGS.NAMES.WELL_KIT = "우물 제작 키트"
STRINGS.RECIPE_DESC.WELL_KIT = "우물이 있는것은 좋은것이다."
STRINGS.NAMES.WELL_SPRINKLER_KIT = "스프링쿨러 제작 키트"
STRINGS.RECIPE_DESC.WELL_SPRINKLER_KIT = "todo"

-- desalinator
STRINGS.NAMES.DESALINATOR = "제염기"
STRINGS.RECIPE_DESC.DESALINATOR = "좋아, 물로 물을 만드는거다."

-- barrel
STRINGS.NAMES.BARREL = "통"
STRINGS.RECIPE_DESC.BARREL = "원숭이 미 포함."

-- brewery
STRINGS.NAMES.BREWERY = "양조기"
STRINGS.RECIPE_DESC.BREWERY = "맛있는 음료를 만들 수 있다. 아마도?"

-- buckets
STRINGS.NAMES.BUCKET_EMPTY = "양동이"
STRINGS.RECIPE_DESC.BUCKET_EMPTY = "비어있는 양동이."
--[[STRINGS.NAMES.BUCKET_CLEAN = "Bucket o' Water"
STRINGS.NAMES.BUCKET_DIRTY = "Bucket o' Dirty Water"
STRINGS.NAMES.BUCKET_SALTY = "Bucket o' Salty Water"
STRINGS.NAMES.BUCKET_ICE = "Ice Bucket"]]

-- campkettle
STRINGS.NAMES.CAMPKETTLE_ITEM = "캠프 주전자 키트"
STRINGS.RECIPE_DESC.CAMPKETTLE_ITEM = "당신이 처음에 쓸 주전자."
STRINGS.NAMES.CAMPKETTLE = "캠프 주전자"

-- kettle
STRINGS.NAMES.KETTLE	= "주전자"
STRINGS.RECIPE_DESC.KETTLE = "당신의 전생의 마지막 것."

-- portablekettle
STRINGS.NAMES.PORTABLEKETTLE_ITEM	= "Portable Kettle"
STRINGS.NAMES.PORTABLEKETTLE = "Portable Kettle"
STRINGS.RECIPE_DESC.PORTABLEKETTLE_ITEM = "It's easy to carry around."

--purification_tablets
--[[STRINGS.NAMES.PURIFICATION_TABLETS = "Purification Tablets"
STRINGS.RECIPE_DESC.PURIFICATION_TABLETS = "TODO"]]

-- tea_trees
STRINGS.NAMES.TEA_TREE = "차나무"
STRINGS.NAMES.DUG_TEA_TREE = "차나무" 
STRINGS.NAMES.TEA_SEED = "차나무 씨앗"
STRINGS.NAMES.TEA_SEED_COOKED = "구운 차나무 씨앗"
STRINGS.NAMES.TEA_SEED_SAPLING = "차나무 묘목"
STRINGS.NAMES.TEALEAVES = "찻잎"
STRINGS.NAMES.TEALEAVES_DRIED = "말린 찻잎."

-- caffeinberry
STRINGS.NAMES.DUG_CAFFEINBERRY = "커피 식물" 
STRINGS.NAMES.CAFFEINBERRY = "커피 식물"
STRINGS.NAMES.CAFFEINBERRY_BEAN = "커피 열매"
STRINGS.NAMES.CAFFEINBERRY_BEAN_COOKED = "구운 커피 열매"
STRINGS.NAMES.SPICE_CAFFEINPEPPER = "후추가루"
STRINGS.RECIPE_DESC.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.NAMES.SPICE_CAFFEINPEPPER_FOOD = "후추를 곁드린 {food}"

-- empty_cup
--[[STRINGS.NAMES.CUP = "Empty Cup"
STRINGS.RECIPE_DESC.CUP = "Container for drinks."]]

-- 정재알약스트링
--[[STRINGS.NAMES.WATER_CLEAN = "Water"
STRINGS.NAMES.WATER_DIRTY = "Dirty Water"
STRINGS.RECIPE_DESC.CUP_WATER = "TODO"
STRINGS.RECIPE_DESC.BOTTLE_WATER = "TODO"]]


-- preparedrink

--[[STRINGS.NAMES.CUP_ITEM = "Cup of {drink}"
STRINGS.NAMES.BOTTLE_ITEM = "Bottle of {drink}"]]
STRINGS.NAMES.WATER_CLEAN_ICE = "언 물"
STRINGS.NAMES.WATER_DIRTY_ICE = "더러운 언 물"
STRINGS.NAMES.WATER_CLEAN = "물"
STRINGS.NAMES.WATER_DIRTY = "더러운 물"
STRINGS.NAMES.WATER_SALTY = "소금물"
STRINGS.NAMES.GOOPYDRINK = "이상한 음료"
STRINGS.NAMES.FRUITJUICE = "믹스과일 주스"
STRINGS.NAMES.BERRIES_JUICE = "배리 주스"
STRINGS.NAMES.POMEGRANATE_JUICE = "석류 주스"
STRINGS.NAMES.BANANA_JUICE = "바나나 주스"
STRINGS.NAMES.FIG_JUICE = "무화과 주스"
STRINGS.NAMES.DRAGONJUICE = "용과 주스"
STRINGS.NAMES.GLOWBERRYJUICE = "빛나는배리 차"
STRINGS.NAMES.CAFFEINBERRY_JUICE = "커피"
STRINGS.NAMES.VEGGIE_TEA = "믹스아채 차"
STRINGS.NAMES.CARROT_TEA = "당근 차"
STRINGS.NAMES.CACTUS_TEA = "선인자 차"
STRINGS.NAMES.MULLED = "Mulled Drink"
STRINGS.NAMES.GREENTEA = "녹차"
STRINGS.NAMES.BLACKTEA = "홍차"
STRINGS.NAMES.BLACKTEA_ICED = "아이이스티"
STRINGS.NAMES.FUER = "보이차"
STRINGS.NAMES.MIXFLOWER = "꽃차"
STRINGS.NAMES.HIBISCUSTEA = "히비스커스 차"
STRINGS.NAMES.CACTUSFLOWER_TEA = "선인장 꽃차"
STRINGS.NAMES.LOTUSTEA = "연꽃차"
STRINGS.NAMES.SUSHIBISCUS = "히비스커스 차?"

-- 유령차 유채이탈 관련 코드
STRINGS.NAMES.GHOSTLY_TEA = "유령 차"
--[[STRINGS.NAMES.BOTTLE_GHOSTLY_TEA = "Bottle of Ghostly Tea"
STRINGS.NAMES.DEATH_BY_TEA = "Ghostly Tea"]]

-- prepareagedrink

STRINGS.NAMES.SPOILED_DRINK = "썩은 음료"
STRINGS.NAMES.SODA = "탄산수"
STRINGS.NAMES.FRUITSODA = "과일 소다"
STRINGS.NAMES.LEMONLIMESODA = "달콤한 소다"
STRINGS.NAMES.COLA = "콜라"
STRINGS.NAMES.COLAQUANTUM = "콜라 퀀텀"
STRINGS.NAMES.CORN_BEER = "옥수수 맥주"
STRINGS.NAMES.MADHU = "꿀술"
STRINGS.NAMES.WINE = "와인"
STRINGS.NAMES.NOBLEWINE = "부유 와인"
STRINGS.NAMES.SPARKLINGWINE = "스파클링 와인"
STRINGS.NAMES.GLOWBERRYWINE = "빛나는배리 와인"
STRINGS.NAMES.KUMIS = "크므스"