STRINGS.UI.CRAFTING_FILTERS.HYDRATION = "Hydration"

STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SLEEP_AND_DETOX = "Sleep & Relieving."
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_MULLED = "Sleep & Strong Relieving"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CAFFINE = "Increased movement speed"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_COLA = "The best drink"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_COLAQUANTUM = "Soul drink"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_INTOXICATION = "Drunk & Reduce"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_INTOXICATION_GLOW = "Drunk & Reduce & Glow"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SUS = "SUS"

STRINGS.ACTIONS.MILK = "Mlik"
STRINGS.ACTIONS.BOIL = "Boil"
STRINGS.ACTIONS.DRINK = "Drink"
--STRINGS.ACTIONS.TAKEWATER = "Fill"
STRINGS.ACTIONS.GIVEWATER = "Put Water In"
--STRINGS.ACTIONS.GET_DRINK = "Get Drink"
STRINGS.ACTIONS.DRAIN = "Drain"
STRINGS.ACTIONS.PURIFY = "Purify"
STRINGS.ACTIONS.MILKINGTOOL = "Milk"
STRINGS.ACTIONS.FERMENT = "Ferment"

-- well drilling
STRINGS.NAMES.WELL_DRILLING ="Well Drill"
STRINGS.NAMES.WELL_DRILLING_ITEM = "Well Drill"
STRINGS.RECIPE_DESC.WELL_DRILLING_ITEM = "Make a hole in the ground."

-- wells & hole & sprinker
STRINGS.NAMES.HOLE = "Hole"
STRINGS.NAMES.WELL = "Well"
STRINGS.NAMES.WELL_SPRINKLER = "sprinkler"

STRINGS.NAMES.WELL_KIT = "Well Parts Kit"
STRINGS.RECIPE_DESC.WELL_KIT = "All's well there's well."
STRINGS.NAMES.WELL_SPRINKLER_KIT = "Sprinkler Parts Kit"
STRINGS.RECIPE_DESC.WELL_SPRINKLER_KIT = "todo."

-- desalinator
STRINGS.NAMES.DESALINATOR = "Desalinator"
STRINGS.RECIPE_DESC.DESALINATOR = "Yes, the water is made of water."

-- barrel
STRINGS.NAMES.BARREL = "Barrel"
STRINGS.RECIPE_DESC.BARREL = "Monkey not included."

-- brewery
STRINGS.NAMES.BREWERY = "Brewery"
STRINGS.RECIPE_DESC.BREWERY = "Can make delicious drinks. maybe?"

-- buckets
STRINGS.NAMES.BUCKET_EMPTY = "Bucket"
STRINGS.RECIPE_DESC.BUCKET_EMPTY = "An empty bucket."
--STRINGS.NAMES.BUCKET_CLEAN = "Bucket o' Water"
--STRINGS.NAMES.BUCKET_DIRTY = "Bucket o' Dirty Water"
--STRINGS.NAMES.BUCKET_SALTY = "Bucket o' Salty Water"
--STRINGS.NAMES.BUCKET_ICE = "Ice Bucket"

-- campkettle
STRINGS.NAMES.CAMPKETTLE_ITEM = "Camp Kettle Kit"
STRINGS.RECIPE_DESC.CAMPKETTLE_ITEM = "Your kettle for first times."
STRINGS.NAMES.CAMPKETTLE = "Camp Kettle"

-- kettle
STRINGS.NAMES.KETTLE	= "Kettle"
STRINGS.RECIPE_DESC.KETTLE = "The last thing of your past life."

-- portablekettle
STRINGS.NAMES.PORTABLEKETTLE_ITEM	= "Portable Kettle"
STRINGS.NAMES.PORTABLEKETTLE = "Portable Kettle"
STRINGS.RECIPE_DESC.PORTABLEKETTLE_ITEM = "It's easy to carry around."

--purification_tablets
--[[STRINGS.NAMES.PURIFICATION_TABLETS = "Purification Tablets"
STRINGS.RECIPE_DESC.PURIFICATION_TABLETS = "TODO"]]

-- tea_trees
STRINGS.NAMES.TEA_TREE = "Tea Tree"
STRINGS.NAMES.DUG_TEA_TREE = "Tea Tree" 
STRINGS.NAMES.TEA_SEED = "Tea Seed"
STRINGS.NAMES.TEA_SEED_COOKED = "Roast Tea Seed"
STRINGS.NAMES.TEA_SEED_SAPLING = "Tea Tree Sapling"
STRINGS.NAMES.TEALEAVES = "Tea Leaves"
STRINGS.NAMES.TEALEAVES_DRIED = "Dried Tea Leaves."

-- caffeinberry
STRINGS.NAMES.DUG_CAFFEINBERRY = "Coffee Plant" 
STRINGS.NAMES.CAFFEINBERRY = "Coffee Plant"
STRINGS.NAMES.CAFFEINBERRY_BEAN = "Coffee Beans"
STRINGS.NAMES.CAFFEINBERRY_BEAN_COOKED = "Roast Coffee Beans"
STRINGS.NAMES.SPICE_CAFFEINPEPPER = "Pepper Crumble"
STRINGS.RECIPE_DESC.SPICE_CAFFEINPEPPER = "TODO"
STRINGS.NAMES.SPICE_CAFFEINPEPPER_FOOD = "Peppered {food}"

-- empty_cup
STRINGS.NAMES.CUP = "Empty Cup"
STRINGS.RECIPE_DESC.CUP = "Container for drinks."

-- 정재알약스트링
--STRINGS.NAMES.WATER_CLEAN = "Water"
--STRINGS.NAMES.WATER_DIRTY = "Dirty Water"
STRINGS.RECIPE_DESC.CUP_WATER = "TODO"
STRINGS.RECIPE_DESC.BOTTLE_WATER = "TODO"

-- preparedrink

--[[STRINGS.NAMES.CUP_ITEM = "Cup of {drink}"
STRINGS.NAMES.BOTTLE_ITEM = "Bottle of {drink}"]]
STRINGS.NAMES.WATER_CLEAN_ICE = "Frozen Water"
STRINGS.NAMES.WATER_DIRTY_ICE = "Frozen Dirty Water"
STRINGS.NAMES.WATER_CLEAN = "Water"
STRINGS.NAMES.WATER_DIRTY = "Dirty Water"
STRINGS.NAMES.WATER_SALTY = "Salty Water"
STRINGS.NAMES.GOOPYDRINK = "Wet Goop"
STRINGS.NAMES.FRUITJUICE = "Mix-Fruit Juice"
STRINGS.NAMES.BERRIES_JUICE = "Berry Juice"
STRINGS.NAMES.POMEGRANATE_JUICE = "Pomegranate Juice"
STRINGS.NAMES.BANANA_JUICE = "Tropic Juice"
STRINGS.NAMES.FIG_JUICE = "Fig Juice"
STRINGS.NAMES.DRAGONJUICE = "DragonFruit Juice"
STRINGS.NAMES.GLOWBERRYJUICE = "Glowberry Juice"
STRINGS.NAMES.CAFFEINBERRY_JUICE = "Coffee"
STRINGS.NAMES.VEGGIE_TEA = "Mix Veggie Tea"
STRINGS.NAMES.CARROT_TEA = "Carrot Tea"
STRINGS.NAMES.CACTUS_TEA = "Cactus Tea"
STRINGS.NAMES.MULLED = "Mulled Drink"
STRINGS.NAMES.GREENTEA = "Green Tea"
STRINGS.NAMES.BLACKTEA = "Black Tea"
STRINGS.NAMES.BLACKTEA_ICED = "Black Tea Iced"
STRINGS.NAMES.FUER = "Fuer Tea"
STRINGS.NAMES.MIXFLOWER = "Flower Medley Tea"
STRINGS.NAMES.HIBISCUSTEA = "Hibiscus Tea"
STRINGS.NAMES.CACTUSFLOWER_TEA = "Cactus Flower Tea"
STRINGS.NAMES.LOTUSTEA = "Lotus Flower Tea"
STRINGS.NAMES.SUSHIBISCUS = "Hibiscus Tea?"

-- 유령차 유채이탈 관련 코드
STRINGS.NAMES.GHOSTLY_TEA = "Ghostly Tea"
--[[STRINGS.NAMES.BOTTLE_GHOSTLY_TEA = "Bottle of Ghostly Tea"
STRINGS.NAMES.DEATH_BY_TEA = "Ghostly Tea"]]

-- prepareagedrink

STRINGS.NAMES.SPOILED_DRINK = "Rotten Drink"
STRINGS.NAMES.SODA = "Sparkling Water"
STRINGS.NAMES.FRUITSODA = "Fruit Soda"
STRINGS.NAMES.LEMONLIMESODA = "Sweet Soda"
STRINGS.NAMES.COLA = "Cola"
STRINGS.NAMES.COLAQUANTUM = "Cola Quantum"
STRINGS.NAMES.CORN_BEER = "Corn Beer"
STRINGS.NAMES.MADHU = "Mead"
STRINGS.NAMES.WINE = "Wine"
STRINGS.NAMES.NOBLEWINE = "Noble Wine"
STRINGS.NAMES.SPARKLINGWINE = "Sparkling Wine"
STRINGS.NAMES.GLOWBERRYWINE = "Glowberry Wine"
STRINGS.NAMES.KUMIS = "Kumis"