_G=GLOBAL
local STRINGS = _G.STRINGS
local rec = STRINGS.RECIPE_DESC
local nm = STRINGS.NAMES
local gen = STRINGS.CHARACTERS.GENERIC.DESCRIBE

--[[TUNING.BEER_ONDRINK = "Oh... I feel drunk"
TUNING.BEER_OFFDRINK = "So refreshing! I feel amazing"
TUNING.POHMEL = "That's disgusting, but I feel better now."
TUNING.STAR_BAKS = "Not Starbaks, but it's okay"
TUNING.TEA_YAWN = ""
TUNING.RED_TEA_SPEEP = ""
TUNING.BARRLE_ENERGY = "Energy - "
TUNING.BARRLE_WATERLEVEL = "%. Water Level "]]--

STRINGS.AW_DRINK = "Drink"

-- well drilling
STRINGS.NAMES.WELL_DRILLING ="Well Drill"
STRINGS.NAMES.WELL_DRILLING_ITEM = "Well Drill"
STRINGS.RECIPE_DESC.WELL_DRILLING_ITEM = "Make a hole in the ground."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_DRILLING = "It's digging a hole."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_DRILLING_ITEM = "To get groundwater, I have to dig a hole first."

-- wells & hole
STRINGS.NAMES.HOLE	  = "Hole"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOLE = "I cannot see the bottom."
STRINGS.NAMES.WELL_ITEM = "Well Parts"
STRINGS.RECIPE_DESC.WELL_ITEM = "Brings deep groundwater."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL_ITEM = "Let's install this in the hole."
STRINGS.NAMES.WELL = "Well"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WELL = "It's easier to get clean water."

-- desalinator
STRINGS.NAMES.DESALINATOR = "Desalinator"
STRINGS.RECIPE_DESC.DESALINATOR = "Remove salt from the sea water."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DESALINATOR = "Now I can get clean water using seawater."

-- barrle
STRINGS.NAMES.BARRLE = "Barrle"
STRINGS.RECIPE_DESC.BARRLE = "A container for storing water."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BARRLE = "I can contain my water here."

-- brewery
STRINGS.NAMES.BREWERY = "Brewery"
STRINGS.RECIPE_DESC.BREWERY = "Can make delicious drinks. maybe?"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BREWERY = "It is one of the ways to store water for a long time."

-- buckets
STRINGS.NAMES.BUCKET	= "Bucket"
STRINGS.RECIPE_DESC.BUCKET = "An empty bucket"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET = "I can fill it with water, or something else."
STRINGS.NAMES.BUCKET_FULL = "Bucket with Water"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_FULL = "It's filled with water."
STRINGS.NAMES.BUCKET_DIRTY = "Bucket with Dirty Water"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_DIRTY = "It's filled with water, but is dirty"
STRINGS.NAMES.BUCKET_SALT = "Bucket with Sea Water"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_SALT = "It's filled with water, but is salty"
STRINGS.NAMES.BUCKET_ICE = "Ice Bucket"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUCKET_ICE = "Now it's useful, but I think I can take it out."

-- campkettle
STRINGS.NAMES.CAMPKETTLE = "Camp Kettle"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAMPKETTLE = "It always need fuel."
STRINGS.RECIPE_DESC.CAMPKETTLE = "Your kettle for first times."

-- kettle
STRINGS.NAMES.KETTLE	= "Kettle"
STRINGS.RECIPE_DESC.KETTLE = "The last thing of your past life."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KETTLE = "Finally, I can make tea now!"

-- portable_kettle
STRINGS.NAMES.PORTABLE_KETTLE_ITEM	= "Portable Kettle"
STRINGS.NAMES.PORTABLE_KETTLE = "Portable Kettle"
STRINGS.RECIPE_DESC.PORTABLE_KETTLE_ITEM = "It's easy to carry around."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLE_KETTLE_ITEM = "I can take it inside my backpack!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLE_KETTLE = "I can take it inside my backpack!"

-- tea_trees
STRINGS.NAMES.TEA_TREE = "Tea Tree"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_TREE = "It's a tree of tea!"
STRINGS.NAMES.DUG_TEA_TREE = "Tea Tree" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_TEA_TREE = "The leaves smell amazing."
STRINGS.NAMES.TEA_SEED = "Tea Seed"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED = "It's a seed of tree tea!"
STRINGS.NAMES.TEA_SEED_COOKED = "Roast Tea Seed"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_SEED_COOKED = "I regret doing this."
STRINGS.NAMES.TEA_SEED_SAPLING = "Tea Tree Sapling"
STRINGS.NAMES.TEALEAVES = "Tea Leaves"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEALEAVES = "That smell is amazing!"
STRINGS.NAMES.TEALEAVES_DRIED = "Dried Tea Leaves."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEALEAVES_DRIED = "The tea scent seems to have become stronger."

-- caffeinberry
STRINGS.NAMES.DUG_CAFFEINBERRY = "Coffee Plant" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_CAFFEINBERRY = "This is a plant I could learn to love."
STRINGS.NAMES.CAFFEINBERRY = "Coffee Plant" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY = "This belongs in the ground!"
STRINGS.NAMES.CAFFEINBERRY_BEAN = "Coffee Beans"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_BEAN = "They could use some roasting."
STRINGS.NAMES.CAFFEINBERRY_BEAN_COOKED = "Roast Coffee Beans" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAFFEINBERRY_BEAN_COOKED = "Heat definitely improved them."

-- preparedrink

STRINGS.NAMES.CUP = "Empty Cup"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP = "For drinking tea!"
STRINGS.RECIPE_DESC.CUP = "Container for drinks."

STRINGS.NAMES.CUP_WATER = "Cup of Water"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_WATER = "I can drink it"

STRINGS.NAMES.CUP_COFFEE = "Cup of Coffee"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_COFFEE = "Delicious!"

STRINGS.NAMES.CUP_TEA = "Cup of Tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_TEA = "I need milk."













STRINGS.NAMES.CUP_RED = "Dragon Drink"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_RED = "Smells really good!"

STRINGS.NAMES.CUP_MONSTER = "Monster Drink"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_MONSTER = "Is it a tea made out of monsters?"

STRINGS.NAMES.CUP_SPIDER = "Cup of spider syrup"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_SPIDER = "Spider syrup? sounds disgusting."

STRINGS.NAMES.CUP_BEER = "Cup of beer"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_BEER = "It's light or dark?"

STRINGS.NAMES.CUP_WINE = "Cup of wine"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_WINE = "That's a typical drink."

STRINGS.NAMES.CUP_MEAD = "Cup of mead"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_MEAD = "It looks sweet, but it's alcohol."

STRINGS.NAMES.TEE_PLANT = "Tea plant"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEE_PLANT = "I can make tea with it, right?"



STRINGS.NAMES.TEE_S = "Herbal tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEE_S = "Smells like real tea!"

STRINGS.NAMES.TEE_M = "Monster tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEE_M = "That smells disgusting!"

STRINGS.NAMES.TEE_G = "Ghostly tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEE_G = "Wendy would love it."
STRINGS.CHARACTERS.WENDY.DESCRIBE.TEE_G = "Abigail, I'm coming!"

STRINGS.NAMES.TEE_R = "Dragon tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEE_R = "Brew of a dragonfruit."

STRINGS.NAMES.TEE_R2 = "Hibiscus tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEE_R2 = "Indian brew."

STRINGS.NAMES.CUP_HIBISCUS = "Cup of hibiscus"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_HIBISCUS = "Sweet Indian tea."

STRINGS.NAMES.CUP_ABI = "Ghostly Drink"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_ABI = "Wendy loves it!"
STRINGS.CHARACTERS.WENDY.DESCRIBE.CUP_ABI = "Abigail I'm coming!"

STRINGS.NAMES.CUP_STRANG = "Strange drink" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_STRANG = "Tastes awful..."
STRINGS.RECIPE_DESC.CUP_STRANG = "Even the name isn't appealing."




STRINGS.NAMES.GRASS_BAG = "Bag of herbs"
STRINGS.RECIPE_DESC.GRASS_BAG = "A magical bag with plants inside."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRASS_BAG = "I should open it."



STRINGS.NAMES.TEA_BERRY = "Berry tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_BERRY = "That smell is tasty."
STRINGS.RECIPE_DESC.TEA_BERRY = "Sweet fruity tea."

STRINGS.NAMES.TEA_CARROT = "Carrtot tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_CARROT = "I hope it will tasty."
STRINGS.RECIPE_DESC.TEA_CARROT = "Vegetarians tea?"

STRINGS.NAMES.TEA_CACTUS = "Cactus flower tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_CACTUS = "I hope tea not will sharp like cactus."
STRINGS.RECIPE_DESC.TEA_CACTUS = "Relax and drink some cold tea."

STRINGS.NAMES.TEA_BANANA = "Banana-tropic tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_BANANA = "I think it need drink when hot."
STRINGS.RECIPE_DESC.TEA_BANANA = "Tea from tropics."

STRINGS.NAMES.TEA_HONEY = "Herbal tea with honey"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA_HONEY = "Now honey not looks useless."
STRINGS.RECIPE_DESC.TEA_HONEY = "Make your tea sweet a bit."

STRINGS.NAMES.CUP_BERRY = "Cup of berry tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_BERRY = "That smell is tasty."

STRINGS.NAMES.CUP_CARROT = "Cup of carrot tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_CARROT = "That not looks tasty."

STRINGS.NAMES.CUP_CACTUS = "Cup of cactus flower tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_CACTUS = "Amazing exotic tea."

STRINGS.NAMES.CUP_BANANA = "Cup of tropic tea"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_BANANA = "I think it need drink when hot."

STRINGS.NAMES.CUP_HONEY = "Cup of tea with honey"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUP_HONEY = "Sweet very sweet."



STRINGS.CUP_WATERDIRTY = "Cup of dirty water"
STRINGS.CUP_WATERRAW = "Cup of raw water"




